local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "ruRU")
if not L then return end 

L["Air"] = "Воздух"
L["Automatic"] = "Авто"
L["Bottom"] = "снизу"
L["Cast Button 1"] = "Кнопка применения 1"
L["Cast Button 2"] = "Кнопка применения 2"
L["Clickthrough"] = "Клик насквозь"
L["Clickthrough Desc"] = "Делает кнопки таймеров прозрачными для нажатий"
L["Crowd Control"] = "Контроль персонажей"
L["Down"] = "Снизу"
L["Earth"] = "Земля"
L["Enable"] = "Включить"
L["Fire"] = "Огонь"
L["Left"] = "Слева"
L["none"] = "Нет"
L["Right"] = "Справа"
L["Top"] = "Сверху"
L["Totems"] = "Тотемы"
L["TotemTimers"] = true
L["Up"] = "верх"
L["Version"] = "Версия"
L["vertical"] = "Вертикальное"
L["Water"] = "Вода"

L["Blizz Style"] = "Стандартный"
L["Color Timer Bars"] = "Окраска таймеров"
L["Color Timer Bars according to their elements."] = "Окрашивать полосы таймеров в соответствии с их стихиями."
L["Debug"] = "Отладка"
L["Displays timer bars underneath times"] = "Показывать полосы времени под таймерами."
L["Fulmination Aura"] = "Аура Сверкание" -- Needs review
L["Fulmination Aura Desc"] = "Отображает ауру вокруг персонажа когда Щит молний стакается 9 раз, используя встроенный PowerAuras"
L["Fulmination Glow"] = "Fulmination Glow" -- Requires localization
L["Fulmination Glow Desc"] = "Lets the Earth Shock cooldown timer and action bar buttons containing Earth Shock glow if Lightning Shield gets to 9 stacks" -- Requires localization
L["General"] = "Общее"
L["Hide Blizzard Timers"] = "Скрыть стандартные таймеры"
L["Hide Default Totem Bar"] = "Скрыть стандартную панель"
L["Hide Default Totem Bar Desc"] = "Если вы снимите галку, вам следует перезагрузить UI"
L["Hide In Vehicles"] = "Скрывать в транспорте"
L["Hide In Vehicles Desc"] = "Скрывать TotemTimers во время управления транспортом. Не изменяйте этот параметр во время управления транспортом"
L["Lock"] = "Зафиксировать"
L["Locks the position of TotemTimers"] = "Зафиксировать TotemTimers"
L["RaidTotems"] = true
L["RaidTotems Desc"] = "Назначить набор тотемов, содержание которого будет определяться аддоном RaidTotems."
L["Red Flash Color"] = "Мерцание красным"
L["RedFlash Desc"] = "Если данная опция включена, заканчивающие свое действие тотемы будут мерцать красным; в других случаях они будут просто появляться и исчезать."
L["Reset All"] = "Сбросить все"
L["Reset Positions"] = "Сбросить позиции"
L["Show Key Bindings"] = "Назначения клавиш"
L["Shows key bindings on totem timers"] = "Отображать назначения клавиш на кнопках таймеров."
L["Shows tooltips on timer and totem buttons"] = "Отображать подсказки при наведении курсора на таймеры или кнопки тотемов."
L["Show Timer Bars"] = "Полосы времени"
L["Show Tooltips"] = "Подсказки"
L["Stop Pulse"] = "Пульсирование при окончании"
L["Stop Pulse Desc"] = "Пульсирование при окончании таймера"
L["Time Color"] = "Цвет времени"
L["Time Font"] = "Шрифт времени"
L["Timer Bar Color"] = "Цвет полосы времени"
L["Timer Bar Texture"] = "Текстура таймера"
L["Timers On Buttons"] = "Таймеры на кнопках"
L["Timers on Buttons is now set in Game Options -> Actionbars -> Show Numbers on Cooldowns"] = "Timers on Buttons is now set in Game Options -> Actionbars -> Show Numbers on Cooldowns" -- Requires localization
L["Tooltips At Buttons"] = "Подсказки у кнопок"
L["Tooltips At Buttons Desc"] = "Показывать подсказки с правой стороны ТТ кнопок."

L["Advanced Options"] = "Расширенные опции"
L["Always Visible Desc"] = "Меню тотемов будет всегда отображаться и будет подвижно как панель команд."
L["Arrangement"] = "Расположение"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "Базовая схема из четырех кнопок таймера, позволяет свободно перемещать их по отдельности."
L["box"] = "Блок"
L["Button Size"] = "Размер кнопки"
L["Cast Button Position"] = "Позиция кнопки применения"
L["Cast Button Position Desc"] = "Установка позиции дополнительных кнопок тотемов, рядом с таймерами."
L["Cast Button Size"] = "Размер кнопки применения"
L["Cast Button Size Desc"] = "Установка размера дополнительных кнопок тотемов относительно размера таймеров."
L["Enable Pulse Bar"] = "Пульсация"
L["Enables the four totem timer buttons and menus"] = "Включить кнопки и меню таймеров четырёх тотемов."
L["horizontal"] = "Горизонтальное"
L["Keybindings desc"] = "Если данная опция включена, то при отображении меню тотемов кнопкам тотемов будут назначены клавиши 1-9.|nЧтобы настройки вступили в силу, вы должны перезайти в игру или перезагрузить UI."
L["loose"] = "Свободное"
L["Mini Icons Desc"] = "Показывает небольшие иконки в нижнем правом углу кнопки таймера, которые отображают иконку пересоздаваемого тотема."
L["Open On Rightclick"] = "Открыть правым кликом"
L["Player Range"] = "Досягаемость игрока"
L["Player Range Desc"] = "Показывает красные точки на таймере тотема, если игрок вне досягаемости."
L["Pulse desc"] = "Показывает внутри таймера статус проковпульсации зеленым цветом, это означает что при заполнение всей иконки таймера зеленым цветом тотем прокает/пульсирует."
L["Raid Member Range"] = "Досягаемость участника рейда"
L["Raid Range Tooltip"] = "Подсказка досягаемости рейда"
L["Range Desc"] = "Показывает в левом нижнем углу, сколько участников рейда не получают эффект от вашего тотема"
L["Reverse Key Bindings"] = "Противоположные клавиши назначения"
L["Reverse Key Desc"] = "Порядок назначения клавиш 9-1 вместо 1-9.|nЧтобы настройки вступилибы в силу, вы должны перезайти в игру или перезагрузить UI."
L["Rightclick Desc"] = "Открывать меню тотемов по правому клику вместо открытия наведением курсора на кнопку таймера. Тотемы могут быть убраны с помощью средней кнопки мыши вместо правого клика."
L["RR Tooltip Desc"] = "При наведении мыши на таймер тотема, показывает список участников рейда, которые вне досягаемости вашего тотема."
L["Scales the timer buttons"] = "Установка размера кнопок таймера."
L["Scaling"] = "Масштабирование"
L["Sets the font size of time strings"] = "Установка размера шрифта строки таймера."
L["Sets the format in which times are displayed"] = "Установка формата отображения времени."
L["Sets the space between timer buttons"] = "Установка промежутка между кнопками таймеров."
L["Sets the space between timer buttons and timer bars"] = "Установка промежутка между кнопками таймеров и полосами времени."
L["Sets the width of timer bars."] = "Установка ширины полос времени."
L["Show Mini Icons"] = "Показать мини иконки"
L["Show Totem Cooldowns"] = "Восстановление тотемов"
L["Spacing"] = "Промежуток"
L["Timer Bar Position"] = "Позиция времени"
L["Timer Bar Position Desc"] = "Установка с какой стороны будет отображаться иконки таймера."
L["Timer Bar Width"] = "Ширина полосы времени"
L["Timer Bar Width Desc"] = "Установка ширины полос времени."
L["Timer Button 1"] = "Таймер 1"
L["Timer Button 2"] = "Таймер 2"
L["Timer Button 3"] = "Таймер 3"
L["Timer Button 4"] = "Таймер 4"
L["Timers"] = "Таймеры"
L["Timers On Buttons Desc"] = "Таймеры будут отображаться на кнопках а не рядом с ними. Если включено, отслеживание оружия будет показывать только время оружия в правой руке при владении двуручным оружием."
L["Time Size"] = "Размер времени"
L["Time Spacing"] = "Промежуток времени"
L["Time Style"] = "Стиль времени"
L["Totem Cooldowns desc"] = "Показывает восстановление всех тотемов с более длительным восстановлением в качестве дополнительных полос таймера."
L["Totem menu direction"] = "Направление меню тотема"
L["Totem menu direction desc"] = "Установка направления открытия меню тотемов. Автоматически определяет направление полагаясь на позицию таймера."
L["Totem Menu Key Bindings"] = "Включить назначение клавиш"
L["Totem Menus Always Visible"] = "Всегда отображать меню тотемов"
L["Totem Menu Spacing"] = "Промежуток меню тотемов"
L["Totem Menu Spacing Desc"] = "Установка промежутка кнопок в меню тотемов. Применимо только когда меню отображается всегда."

L["Ankh Tracker"] = "Таймер Восстания из мертвых"
L["Ankh Tracker Desc"] = "Показывает оставшееся время восстановления вашей способности реинкарнации, а также выводит количество крестов в ваших сумках. Также используется для сохранения и загрузки наборов тотемов."
L["Button 4"] = "Кнопка 4"
L["EarthShieldDesc"] = "Отображать остаток времени Щита Земли и его заряды. Может быть использован для применения Щита Земли."
L["EarthShieldOptionsDesc"] = "Если 'пересоздать' отмечено в опциях для кнопки мыши, щит будет применяться на последнюю персону, на которую он был наложен вне боя, или персона будет задаваться модификацией RaidTotems."
L["Earth Shield Tracker"] = "Отслеживание Щита Земли"
L["ES Charges only"] = "Charges only" -- Requires localization
L["ES Charges only desc"] = "Disables the time display and shows ES charges in its place|nChanges take effect the next time you cast ES" -- Requires localization
L["ES Main Tank Desc"] = "On mouseover shows a menu containing up to 4 main tanks of your raid/party" -- Requires localization
L["ES Main Tank menu"] = "Main Tank menu" -- Requires localization
L["esrecast"] = "пересоздать (последняя цель/RaidTotems)"
L["Leftclick"] = "Левый клик"
L["Middle Button"] = "Средняя кнопка"
L["Rightclick"] = "Правый клик"
L["Shield Tracker"] = "Отслеживание щита"
L["Trackers"] = "Отслеживание"
L["Weapon Buff Tracker"] = "Отслеживание усилений на оружии"
L["WeaponDesc"] = "Отображать остаток времени ваших усилений оружия. Левый клик применяет выбранное усиление, правый клик открывает меню для выбора усиления. Иконка отображающая два улучшения, по ней первый левый клик применит улучшение на левое оружие, второй левый клик на правое."

L["Color"] = "Цвет"
L["disabled warnings desc"] = "Сообщения об истечении эффектов будут отображаться, даже если отслеживание отключено."
L["EarthShield warnings"] = "Сообщения о щите земли"
L["Maelstrom notification"] = "Сообщения о Водовороте"
L["Messages"] = "Сообщения"
L["Shield expiration warnings"] = "Сообщения о спадении щита"
L["Show warnings of disabled trackers"] = "Вывод предупреждений отключенных отслеживаний"
L["Sound"] = "Звук"
L["Totem Desctruction Desc"] = "Сообщать если тотем был уничтожен до его истечения."
L["Totem Destruction Message"] = "Сообщения об уничтожении тотема"
L["Totem Expiration Desc"] = "Сообщать после истечения тотема."
L["Totem Expiration Message"] = "Сообщения об исчезании тотемов"
L["Totem Expiration Warning"] = "Предупреждения об исчезании тотемов"
L["Totem Warning Desc"] = "Предупреждать за 10 секунд до исчезания тотема."
L["Warnings"] = "Предупреждение"
L["Weapon buff warnings"] = "Сообщения об усилениях оружия"

L["Cooldowns"] = "Кулдауны" -- Needs review
L["Duration"] = "Длительность"
L["ECD Button Size"] = "Размер кнопки ECD"
L["ECD Font Size"] = "Высота шрифта ECD"
L["EnhanceCDs"] = true
L["Flame Shock on top"] = "Огненный шок сверху"
L["Flame Shock on top desc"] = "Показывает полоски Огненного Шока и Водоворота над кулдаунами"
L["Hide OOC Desc"] = "Изменение этой настройки вступит в силу после следующего боя"
L["Hide out of combat"] = "Скрыть вне боя"
L["Lava Surge Aura"] = "Аура Волны Лавы"
L["Lava Surge Aura Desc"] = "Отображает ауру вокруг персонажа если срабатывает Волна Лавы, используя встроенный PowerAuras"
L["Lava Surge Glow"] = "Сверкание Волны Лавы"
L["Lava Surge Glow Desc"] = "Позволяет таймеру Выброса Лавы и всем экшнбарам с Выбросом Лавы сверкать при срабатывании Волны Лавы"
L["Long Cooldowns"] = "Долгие кулдауны" -- Needs review
L["Maelstrom Bar Height"] = "Высота полосы водоворота"
L["OOC Alpha"] = "Прозрачность вне боя"
L["OOC Alpha Desc"] = "Настройка прозрачности кнопок вне боя, 0 = прозрачный, 1 = непрозрачный"
L["Show OmniCC counters"] = "Показывать счетчики OmniCC"
L["Spells"] = "Заклинания" -- Needs review

L["Arena"] = "Арена" -- Needs review
L["Battleground"] = "Поле боя" -- Needs review
L["Copy All"] = "Копировать все" -- Needs review
L["Copy CC Settings"] = "Copy CC Settings" -- Requires localization
L["Copy EnhanceCDs Settings"] = "Copy EnhanceCDs Settings" -- Requires localization
L["Copy Frame Positions"] = "Копировать позиции окна" -- Needs review
L["Copy From"] = "Скопировать из" -- Needs review
L["Copy General Settings"] = "Копировать общие настройки" -- Needs review
L["Copy Settings"] = "Копировать настройки" -- Needs review
L["Copy To"] = "Копировать в" -- Needs review
L["Copy Totem Settings"] = "Копировать настройки тотемов" -- Needs review
L["Copy Totem Timer Settings"] = "Копировать настройки таймеров тотемов" -- Needs review
L["Copy Tracker Settings"] = "Копировать настройки трекера" -- Needs review
L["Copy Warnings"] = "Копировать предупреждения" -- Needs review
L["Create Profile"] = "Создать профиль" -- Needs review
L["default"] = "По умолчанию" -- Needs review
L["Delete Profile"] = "Удалить профиль" -- Needs review
L["Manage Profiles"] = "Управление профилями" -- Needs review
L["New Name"] = "Новое имя" -- Needs review
L["Party"] = "Группа" -- Needs review
L["Profile"] = "Профиль" -- Needs review
L["Profile already exists."] = "Профиль уже существует." -- Needs review
L["Profiles"] = "Профили" -- Needs review
L["Raid"] = "Рейд" -- Needs review
L["Really delete profile?"] = "Действительно удалить профиль?" -- Needs review
L["Really reset frame positions?"] = "Действительно сбросить позиции окон?" -- Needs review
L["Reset Frame Positions"] = "Сбросить позиции окон" -- Needs review
L["Reset Profile"] = "Сбросить профиль" -- Needs review
L["Select Profiles"] = "Выбрать профиль" -- Needs review
L["Solo"] = "Соло" -- Needs review
L["You cannot delete the default profile."] = "Вы не можете удалить профиль по умолчанию." -- Needs review
L["You need to enter a profile name first."] = "Вам необходимо ввести имя профиля первым." -- Needs review
