-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "koKR")
if not L then return end

L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = [=[
Alt+우클릭으로 노트 추가]=]
L["(No Title)"] = "(제목 없음)"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00힌트: |cffeda55fCtrl+Shift+드래그|cFF00FF00하면 노트를 이동할 수 있습니다"
L["Add Handy Note"] = "노트 추가"
L["Add this location to TomTom waypoints"] = "TomTom 웨이포인트에 현재 위치 추가"
L["Configuration for each individual plugin database."] = "각각의 플러그인 데이터베이스에 관한 설정입니다."
L["Delete Handy Note"] = "노트 삭제"
L["Description/Notes:"] = "설명/메모:"
L["Edit Handy Note"] = "노트 수정"
L["Enable HandyNotes"] = "HandyNotes 사용"
L["Enable or disable HandyNotes"] = "애드온을 사용하거나 끕니다"
L["ERROR_CREATE_NOTE1"] = [=[HandyNote는 현재 지역 정보를 얻을수가 없어서 노트를 만들수 없습니다.
일반적인 이유로는 플레이어가 있는 지역에 지도가 없어서 입니다.]=]
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "아이콘 투명도"
L["Icon Scale"] = "아이콘 크기"
L["Minimap Icon Alpha"] = "미니맵 아이콘 투명도"
L["Minimap Icon Scale"] = "미니맵 아이콘 크기"
L["Overall settings"] = "종합 설정"
L["Overall settings that affect every database"] = "모든 데이터에 관해 설정합니다"
L["Plugin databases"] = "플러그인 데이터베이스"
L["Plugins"] = "플러그인"
L["Portal"] = "포탈"
L["Show on continent map"] = "대륙 지도에 표시"
L["Show the following plugins on the map"] = "지도에 플러그인 표시"
L["Syntax:"] = "구문:"
L["The alpha transparency of the icons"] = "아이콘의 투명도를 변경합니다"
L["The overall alpha transparency of the icons on the Minimap"] = "미니맵에 표시되는 모든 아이콘의 투명도를 변경합니다"
L["The overall alpha transparency of the icons on the World Map"] = "세계 지도에 표시되는 모든 아이콘의 투명도를 변경합니다"
L["The overall scale of the icons on the Minimap"] = "미니맵에 표시되는 모든 아이콘의 크기를 변경합니다"
L["The overall scale of the icons on the World Map"] = "세계 지도에 표시되는 모든 아이콘의 크기를 변경합니다"
L["The scale of the icons"] = "아이콘의 크기"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "이 설정은 HandyNotes의 전체적인 표시를 조절합니다. 이 곳의 아이콘 크기와 투명도는 플러그인의 크기와 투명도에 곱해집니다."
L["These settings control the look and feel of the HandyNotes icons."] = "HandyNotes 아이콘의 표시를 조절하는 설정입니다."
L["Title"] = "제목"
L["World Map Icon Alpha"] = "세계 지도 아이콘 투명도"
L["World Map Icon Scale"] = "세계 지도 아이콘 크기"

