-- Not translations
MONKEYBUDDY_TITLE							= "MonkeyBuddy";
MONKEYBUDDY_VERSION							= "CY 汉化";
MONKEYBUDDY_FRAME_TITLE						= MONKEYBUDDY_TITLE .. " - " .. MONKEYBUDDY_VERSION;
MONKEYBUDDY_QUEST_TITLE						= "MonkeyQuest";
MONKEYBUDDY_SPEED_TITLE						= "MonkeySpeed";
MONKEYBUDDY_CLOCK_TITLE						= "MonkeyClock";
MONKEYBUDDY_INFO_COLOUR						= "|cffffff00";
MONKEYBUDDY_GUI_ICON						= "\124TInterface\\AddOns\\MonkeyLibrary\\Textures\\MonkeyBuddyIcon.tga:0\124t "
BINDING_HEADER_MONKEYBUDDY					= MONKEYBUDDY_TITLE;

-- English, the default
MONKEYBUDDY_DESCRIPTION						= "帮助您配置 MonkeyMods.";
MONKEYBUDDY_LOADED_MSG						= MONKEYBUDDY_INFO_COLOUR .. MONKEYBUDDY_TITLE .. " v" .. MONKEYBUDDY_VERSION .. "加载";

MONKEYBUDDY_TOOLTIP_CLOSE					= "关闭";
MONKEYBUDDY_RESET_ALL						= "全部重置";
MONKEYBUDDY_RESET_TO_BLIZZARD_STYLE			= "暴雪风格";
MONKEYBUDDY_GEPY_STYLE						= "DaMaGepy 风格";
MONKEYBUDDY_RESET							= "重置";

MONKEYBUDDY_GUI_TEXT						="此加载项允许您轻松配置 MonkeyMods"
MONKEYBUDDY_GUI_MBLOADED					= MONKEYBUDDY_GUI_ICON .. "MonkeyBuddy 已成功加载!"
MONKEYBUDDY_GUI_MMINSTALLED					="安装 MonkeyMods:"
MONKEYBUDDY_GUI_MBMINIMAP					="显示 MonkeyBuddy 小地图图标"
MONKEYBUDDY_GUI_MQEXTRA						="MonkeyQuest 额外功能:"
MONKEYBUDDY_GUI_MQEDAILY					="在标题中显示每日任务数量"
MONKEYBUDDY_GUI_MBOPENCFG					="点击下列按钮开启"

-- defs for MonkeyQuest
MONKEYBUDDY_QUEST_OPEN						= "打开 MonkeyQuest";
MONKEYBUDDY_QUEST_SHOWHIDDEN				= "显示隐藏项";
MONKEYBUDDY_QUEST_USEOVERVIEWS				= "任务没有目标时显示概述";
MONKEYBUDDY_QUEST_HIDEHEADERS				= "如果不显示隐藏项，则隐藏区域标题";
MONKEYBUDDY_QUEST_ALWAYSHEADERS				= "始终显示区域标题";
MONKEYBUDDY_QUEST_HIDEBORDER				= "隐藏边框";
MONKEYBUDDY_QUEST_GROWUP					= "向上展开";
MONKEYBUDDY_QUEST_SHOWNUMQUESTS				= "显示任务数";
MONKEYBUDDY_QUEST_LOCK						= "锁定 MonkeyQuest";
MONKEYBUDDY_QUEST_COLOURTITLEON				= "依据难度显示任务标题颜色";
MONKEYBUDDY_QUEST_HIDECOMPLETEDQUESTS		= "隐藏已完成的任务";
MONKEYBUDDY_QUEST_HIDECOMPLETEDOBJECTIVES	= "隐藏已完成的任务目标";
MONKEYBUDDY_QUEST_SHOWTOOLTIPOBJECTIVES		= "在鼠标提示中显示任务目标完整度";
MONKEYBUDDY_QUEST_ALLOWRIGHTCLICK			= "允许右击标题栏打开 MonkeyBuddy";
MONKEYBUDDY_QUEST_HIDETITLEBUTTONS			= "隐藏标题按钮";
MONKEYBUDDY_QUEST_HIDETITLE					= "隐藏标题 (任务清单) 文字";
MONKEYBUDDY_QUEST_FONT						= "字体:";
MONKEYBUDDY_QUEST_CRASHBORDER				= "使用金色边框";
MONKEYBUDDY_QUEST_SHOWNOOBTIPS				= "显示对新手有帮助的提示";
MONKEYBUDDY_QUEST_SHOWZONEHIGHLIGHT			= "显示任务区域的突出显示";
MONKEYBUDDY_QUEST_SHOWQUESTLEVEL			= "显示任务等级";
MONKEYBUDDY_QUEST_WORKCOMPLETE				= "启用>任务完成<声音";
MONKEYBUDDY_QUEST_COLOURSUBOBJECTIVES		= "依据进度显示任务目标颜色";
MONKEYBUDDY_QUEST_ITEMSENABLED				= "显示任务物品按钮"
MONKEYBUDDY_QUEST_ITEMSONLEFT				= "任务物品显示在左侧";
MONKEYBUDDY_QUEST_HIDEHEADER				= "仅在鼠标悬停时显示标题/标题按钮"
MONKEYBUDDY_QUEST_HIDEQUESTSENABLED			= "如果不显示隐藏项目，可通过右键单击隐藏任务"

MONKEYBUDDY_QUEST_QUESTTITLECOLOUR			= "任务标题";
MONKEYBUDDY_QUEST_HEADEROPENCOLOUR			= "打开区域标题";
MONKEYBUDDY_QUEST_HEADERCLOSEDCOLOUR		= "关闭区域标题";
MONKEYBUDDY_QUEST_OVERVIEWCOLOUR			= "任务概述";
MONKEYBUDDY_QUEST_SPECIALOBJECTIVECOLOUR	= "特殊任务目标";
MONKEYBUDDY_QUEST_INITIALOBJECTIVECOLOUR	= "任务目标进度为 0%";
MONKEYBUDDY_QUEST_MIDOBJECTIVECOLOUR		= "任务目标进度为 50%";
MONKEYBUDDY_QUEST_COMPLETEOBJECTIVECOLOUR	= "任务目标进度为 <100%";
MONKEYBUDDY_QUEST_FINISHOBJECTIVECOLOUR		= "任务目标完成";
MONKEYBUDDY_QUEST_ZONEHIGHLIGHTCOLOUR		= "当前区域突出显示";

MONKEYBUDDY_QUEST_FRAMEALPHASLIDER			= "整体不透明度";
MONKEYBUDDY_QUEST_ALPHASLIDER				= "背景不透明度";
MONKEYBUDDY_QUEST_HIGHLIGHTALPHASLIDER		= "突出显示区域不透明度";
MONKEYBUDDY_QUEST_WIDTHSLIDER				= "框架宽度";
MONKEYBUDDY_QUEST_FONTSLIDER				= "文字大小";
MONKEYBUDDY_QUEST_PADDINGSLIDER				= "文字间距";

-- defs for MonkeySpeed
MONKEYBUDDY_SPEED_OPEN						= "Open MonkeySpeed";
MONKEYBUDDY_SPEED_PERCENT					= "Show speed as a percent";
MONKEYBUDDY_SPEED_BAR						= "Show speed as a background colour";
MONKEYBUDDY_SPEED_LOCK						= "Lock the MonkeySpeed frame";
MONKEYBUDDY_SPEED_ALLOWRIGHTCLICK			= "Allow right click to open MonkeyBuddy";

MONKEYBUDDY_SPEED_WIDTHSLIDER				= "Frame Width";
MONKEYBUDDY_SPEED_HEIGHTSLIDER				= "Frame Height";

-- defs for MonkeyClock
MONKEYBUDDY_CLOCK_OPEN						= "Open MonkeyClock";
MONKEYBUDDY_CLOCK_HIDEBORDER				= "Hide the border";
MONKEYBUDDY_CLOCK_USEMILITARYTIME			= "Use 24 hour clock";
MONKEYBUDDY_CLOCK_LOCK						= "Lock the MonkeyClock frame";
MONKEYBUDDY_CLOCK_CHATALARM					= "Use the alarm message in the chat window";
MONKEYBUDDY_CLOCK_DIALOGALARM				= "Use the alarm dialog box with snooze button";
MONKEYBUDDY_CLOCK_ALLOWRIGHTCLICK			= "Allow right click to open MonkeyBuddy";

MONKEYBUDDY_CLOCK_HOURSLIDER				= "Hour Offset";
MONKEYBUDDY_CLOCK_MINUTESLIDER				= "Minute Offset";

MONKEYBUDDY_CLOCK_ALARMHOURSLIDER			= "Alarm Hour";
MONKEYBUDDY_CLOCK_ALARMMINUTESLIDER			= "Alarm Minute";

-- bindings
BINDING_NAME_MONKEYBUDDY_OPEN				= "Open/Close the config frame";

if (GetLocale() == "zhTW") then

MONKEYBUDDY_TITLE							= "MQ 任務清單-設定選項";
MONKEYBUDDY_DESCRIPTION						= "幫助你設定 MQ 任務清單";
MONKEYBUDDY_LOADED_MSG						= MONKEYBUDDY_INFO_COLOUR .. MONKEYBUDDY_TITLE .. " v" .. MONKEYBUDDY_VERSION .. " 已載入";

MONKEYBUDDY_TOOLTIP_CLOSE					= "關閉";
MONKEYBUDDY_RESET_ALL						= "全部重置";
MONKEYBUDDY_RESET_TO_BLIZZARD_STYLE			= "暴雪風格";
MONKEYBUDDY_GEPY_STYLE						= "DaMaGepy 風格";
MONKEYBUDDY_RESET							= "重置";

MONKEYBUDDY_GUI_TEXT						="這個插件讓你可以輕鬆的設定 MQ 任務清單"
MONKEYBUDDY_GUI_MBLOADED					= MONKEYBUDDY_GUI_ICON .. "MQ 任務清單-設定選項載入成功!"
MONKEYBUDDY_GUI_MMINSTALLED					="已安裝的 Monkey 模組:"
MONKEYBUDDY_GUI_MBMINIMAP					="顯示小地圖按鈕"
MONKEYBUDDY_GUI_MQEXTRA						="MQ 任務清單額外功能:"
MONKEYBUDDY_GUI_MQEDAILY					="在標題中顯示每日任務數量"
MONKEYBUDDY_GUI_MBOPENCFG					="點擊下列按鈕開啟"

-- defs for MonkeyQuest
MONKEYBUDDY_QUEST_OPEN						= "打開 MQ 任務清單";
MONKEYBUDDY_QUEST_SHOWHIDDEN				= "顯示隱藏項目";
MONKEYBUDDY_QUEST_USEOVERVIEWS				= "沒有任務目標時顯示任務簡介";
MONKEYBUDDY_QUEST_HIDEHEADERS				= "沒有顯示隱藏項目時也要隱藏區域標題";
MONKEYBUDDY_QUEST_ALWAYSHEADERS				= "總是顯示區域標題，永遠";
MONKEYBUDDY_QUEST_HIDEBORDER				= "隱藏邊框";
MONKEYBUDDY_QUEST_GROWUP					= "清單往上方增長";
MONKEYBUDDY_QUEST_SHOWNUMQUESTS				= "顯示任務數量";
MONKEYBUDDY_QUEST_LOCK						= "鎖定 MQ 任務清單框架";
MONKEYBUDDY_QUEST_COLOURTITLEON				= "依據難度顯示任務標題顏色";
MONKEYBUDDY_QUEST_HIDECOMPLETEDQUESTS		= "隱藏已完成的任務";
MONKEYBUDDY_QUEST_HIDECOMPLETEDOBJECTIVES	= "隱藏已完成的任務目標";
MONKEYBUDDY_QUEST_SHOWTOOLTIPOBJECTIVES		= "在滑鼠提示中顯示任務目標完成度";
MONKEYBUDDY_QUEST_ALLOWRIGHTCLICK			= "允許使用滑鼠右鍵點擊來開啟設定選項";
MONKEYBUDDY_QUEST_HIDETITLEBUTTONS			= "隱藏標題按鈕";
MONKEYBUDDY_QUEST_HIDETITLE					= "隱藏標題 (MQ 任務清單) 文字";
MONKEYBUDDY_QUEST_FONT						= "字體:";
MONKEYBUDDY_QUEST_CRASHBORDER				= "使用金色邊框";
MONKEYBUDDY_QUEST_SHOWNOOBTIPS				= "顯示對新手有幫助的滑鼠提示";
MONKEYBUDDY_QUEST_SHOWZONEHIGHLIGHT			= "顯示任務區域的顯著標示";
MONKEYBUDDY_QUEST_SHOWQUESTLEVEL			= "顯示任務等級";
MONKEYBUDDY_QUEST_WORKCOMPLETE				= "啟用 >工作完成< 音效";
MONKEYBUDDY_QUEST_COLOURSUBOBJECTIVES		= "依據進度顯示任務目標顏色";
MONKEYBUDDY_QUEST_ITEMSENABLED				= "顯示任務物品按鈕"
MONKEYBUDDY_QUEST_ITEMSONLEFT				= "任務物品顯示在左側";
MONKEYBUDDY_QUEST_HIDEHEADER				= "只有滑鼠指向時才顯示標題/標題按鈕"
MONKEYBUDDY_QUEST_HIDEQUESTSENABLED			= "沒有顯示隱藏項目時，可點擊滑鼠右鍵來隱藏任務"

MONKEYBUDDY_QUEST_QUESTTITLECOLOUR			= "任務標題";
MONKEYBUDDY_QUEST_HEADEROPENCOLOUR			= "打開的區域標題";
MONKEYBUDDY_QUEST_HEADERCLOSEDCOLOUR		= "關閉的區域標題";
MONKEYBUDDY_QUEST_OVERVIEWCOLOUR			= "任務簡介";
MONKEYBUDDY_QUEST_SPECIALOBJECTIVECOLOUR	= "特殊任務目標";
MONKEYBUDDY_QUEST_INITIALOBJECTIVECOLOUR	= "任務目標進度為 0%";
MONKEYBUDDY_QUEST_MIDOBJECTIVECOLOUR		= "任務目標進度達 50%";
MONKEYBUDDY_QUEST_COMPLETEOBJECTIVECOLOUR	= "任務目標進度 <100%";
MONKEYBUDDY_QUEST_FINISHOBJECTIVECOLOUR		= "任務目標完成";
MONKEYBUDDY_QUEST_ZONEHIGHLIGHTCOLOUR		= "當前區域顯著標示";

MONKEYBUDDY_QUEST_FRAMEALPHASLIDER			= "整體不透明度";
MONKEYBUDDY_QUEST_ALPHASLIDER				= "背景不透明度";
MONKEYBUDDY_QUEST_HIGHLIGHTALPHASLIDER		= "區域顯著標示不透明度";
MONKEYBUDDY_QUEST_WIDTHSLIDER				= "清單寬度";
MONKEYBUDDY_QUEST_FONTSLIDER				= "文字大小";
MONKEYBUDDY_QUEST_PADDINGSLIDER				= "文字間距";

-- bindings
BINDING_NAME_MONKEYBUDDY_OPEN				= "開啟/關閉設定選項";

end
