---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/6/26 10:30
---
local L = WebDKP.translations

L.CLASS_LOCALIZED_TO_ENG_MAP = {}
for className, localizedClassName in pairs(LOCALIZED_CLASS_NAMES_MALE) do
    L.CLASS_LOCALIZED_TO_ENG_MAP[localizedClassName] = string.lower(className):gsub("^%l", string.upper)
end

L.CLASS_ALIAS_TO_ENG_MAP = {}

--MinimapDropDown
L.WEBDKP_MINIMAPDROPDOWN_DKPTABLE = "DKP Table"
L.WEBDKP_MINIMAPDROPDOWN_BIDDING = "Bidding"
L.WEBDKP_MINIMAPDROPDOWN_TIMEDAWARDS = "Timed Awards"
L.WEBDKP_MINIMAPDROPDOWN_OPTIONS = "Options"
L.WEBDKP_MINIMAPDROPDOWN_HELP = "Help"
L.WEBDKP_MINIMAPDROPDOWN_SYNCHSETTINGS = "Synch Settings"
L.WEBDKP_MINIMAPDROPDOWN_VIEWLOG = "View Log"
L.WEBDKP_MINIMAPDROPDOWN_RAIDLOG = "Raid Log"
L.WEBDKP_MINIMAPDROPDOWN_CHARRAIDLOG = "Char Raid Log"

--Table
L.WEBDKP_HEADER = "DKP Table:"
L.WEBDKP_FRAME_NAME_COLUMN = "Name"
L.WEBDKP_FRAME_CLASS_COLUMN = "Class"
L.WEBDKP_FRAME_DKP_COLUMN = "DKP"
L.WEBDKP_FRAME_GUILDRANK_COLUMN = "Guild Rank"

--TABS
L.TAB_FILTER = "Filters"
L.TAB_AWARD_DKP = "Award DKP"
L.TAB_AWARD_ITEM = "Award Item"
L.TAB_STANDBY = "Standby"

--TAB FOR FILTER
L.FILTER_HEADER = "Filters:"
L.FILTER_CLASS_WARLOCK = "Warlock"
L.FILTER_CLASS_WARRIOR = "Warrior"
L.FILTER_CLASS_HUNTER = "Hunter"
L.FILTER_CLASS_MAGE = "Mage"
L.FILTER_CLASS_PRIEST = "Priest"
L.FILTER_CLASS_DRUID = "Druid"
L.FILTER_CLASS_PALADIN = "Paladin"
L.FILTER_CLASS_SHAMAN = "Shaman"
L.FILTER_CLASS_ROGUE = "Rogue"
L.FILTER_CLASS_DEATH_KNIGHT = "Death Knight"

L.FILTER_CLASS_CASTERS = "Casters"
L.FILTER_CLASS_MELEE = "Melee"
L.FILTER_CLASS_HEALER = "Healer"
L.FILTER_CLASS_CHAIN = "Chain"
L.FILTER_CLASS_CLOTH = "Cloth"
L.FILTER_CLASS_LEATHER = "Leather"
L.FILTER_CLASS_PLATE = "Plate"

L.FILTER_CHECK_ALL = "Check All"
L.FILTER_UNCHECK_ALL = "Uncheck All"
L.FILTER_PLAYERS_IN_GROUP = "In current group"
L.FILTER_STANDBY_PLAYERS = "Include Standby Players"

L.DKP_TABLE_SELECT_ALL = "Select All"
L.DKP_TABLE_DESELECT_ALL = "Deselect All"
L.DKP_TABLE_SAVE_LOG = "Save Log File"
L.DKP_TABLE_Refresh = "Refresh Group"

--TAB FOR AWARD DKP
L.AWARD_DKP_HEADER = "Award DKP:"
L.AWARD_DKP_INFO1 = "Select recieving players on left and enter\n award information below."
L.AWARD_DKP_DECAY_HEADER = "DKP Decay:"
L.AWARD_DKP_INFO3 = "Select recieving players on left."
L.AWARD_DKP_REASON_LABEL = "Reason:"
L.AWARD_DKP_POINTS_LABEL = "Points: (Use negative # to deduct points)"
L.AWARD_DKP_AWARD_POINTS = "Award DKP"
L.AWARD_DKP_DECAY_LABEL = "Decay value:(.4), (-.4) etc"
L.AWARD_DKP_DECAY_BUTTON = "Award Decay"

--TAB FOR AWARD ITEM
L.AWARD_ITEM_HEADER = "Award Item:"
L.AWARD_ITEM_INFO1 = "Select recieving player from table on left\n and enter item information below."
L.AWARD_ITEM_ITEM_NAME_LABEL = "Item Name:"
L.AWARD_ITEM_ITEM_COST_LABEL = "Item Cost: (Positive numbers only)"
L.AWARD_ITEM_ITEM_COST_LABEL2 = "(Include % after for percents (50%)"
L.AWARD_ITEM_AWARD_ITEM = "Award Item"

--TAB FOR STANDBY
L.STANDBY_HEADER = "Standby Players:"
L.STANDBY_INFO1 = "Players can add or remove thesmelves with:\n !standby add or !standby del"
L.STANDBY_ADD_STANDBY_LABEL = "Player Name:"
L.STANDBY_ADD_TO_STANDBY = "Add"
L.STANDBY_DEL_STANDBY = "Remove"
L.STANDBY_RESET_STANDBY = "Reset"
L.STANDBY_RESET_STANDBY_LABEL = "Reset All Standby Players:"
L.STANDBY_ENABLE_STANDBY_ZEROSUM = "Enable Zerosum for Standby Players"
L.STANDBY_ENABLE_STANDBY_TIMED = "Enable Timed Awards for Standby"

--BID
L.BID_TITLE = "WebDKP Bidding"
L.BID_ITEM_LABEL = "Item:"
L.BID_STARTING_BID_LABEL = "Starting Bid:"
L.BID_TIME_LABEL = "Bid/Roll Time:"
L.BID_TIME_HINT = "(in seconds - use 0 for no limit)"
L.BID_BID_BUTTON = "Start the Bidding!"
L.BID_ROLL_BUTTON = "Start the Rolls!"
L.BID_TOP3_BUTTON = "Announce Top 3 Bids"
L.BID_TABLE_HEADER = "Received Bids/Rolls:"
L.BID_TABLE_COLUMN_NAME_LABEL = "Name"
L.BID_TABLE_COLUMN_BID_LABEL = "Bid"
L.BID_TABLE_COLUMN_DKP_LABEL = "DKP"
L.BID_TABLE_COLUMN_POST_LABEL = "DKP - Bid"
L.BID_TABLE_COLUMN_ROLL_LABEL = "Rolls"
L.BID_TABLE_COLUMN_SPEC_LABEL = "Main/Offspec"
L.BID_TABLE_COLUMN_GUILD_RANK_LABEL = "Guild Rank"
L.BID_AWARD = "Award Item To Player"
L.FORMAT_MSG_ROLLING_PATTERN = "(.+) rolls (%d+) %((%d+)%-(%d+)%)"


--Timed Award
L.WEBDKP_TIMEDAWARDFRAME_TITLE = "Timed Award"
L.WEBDKP_TIMEDAWARDFRAME_TEXT = "Timed awards allow you to automatically award DKP/EP after a set time has passed"
L.WEBDKP_TIMEDAWARDFRAME_DKP_LABEL = "Points:"
L.WEBDKP_TIMEDAWARDFRAME_TIME_LABEL = "Time:"
L.WEBDKP_TIMEDAWARDFRAME_TIME_HINT = "(in minutes)"
L.WEBDKP_TIMEDAWARDFRAME_LOOPTIMER_LABEL = "Repeat Award:"
L.WEBDKP_TIMEDAWARDFRAME_RESETBUTTON = "Reset"
L.WEBDKP_TIMEDAWARDFRAME_STARTSTOPBUTTON = "Start"
L.WEBDKP_TIMEDAWARDFRAME_MINIBUTTON = "Mini Timer"

--Options
L.WEBDKP_OPTIONSFRAME_TITLE = "WebDKP Options"
--WebDKP_GeneralOptions_Frame
L.WEBDKP_GENERALOPTIONS_FRAME_TITLE = "General Options:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO1 = "Autofill Item Details From Drops:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO2 = "ZeroSum DKP:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO3 = "Auto Award for Boss Kills:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO4 = "Enable or Disable WebDKP"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO5 = "Enable or Disable Alt+Click to bring up bidding window"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO6 = "Ignore Whispers from Non Party/Raid Members"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO7 = "Specify a DKP Cap"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO8 = "Effort Points / Gear Points (EPGP):"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAUTOFILLENABLED_LABEL = "Autofill Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAUTOAWARDENABLED_LABEL = "AutoAward Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEZEROSUMENABLED_LABEL = "ZeroSum Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAWARDBOSSDKP_LABEL = "Enable/Disable"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEALTCLICK_LABEL = "Alt+Click Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEIGNWHISPERS_LABEL = "Ignore Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEDKPCAP_LABEL = "DKP Cap Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_DKPCAPLIMIT_LABEL = "Cap Limit:"
L.WEBDKP_GENERALOPTIONS_FRAME_BOSSDKP_LABEL = "DKP Amount:"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEENABLED_LABEL = "WebDKP Enabled"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEENABLED_LABEL = "WebDKP Enabled"
--WebDKP_BiddingOptions_Frame
L.WEBDKP_BIDDINGOPTIONS_FRAME_INFO1 = "Bidding Options:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANNOUNCERAID_LABEL = "Announce in Raid Warning"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDCONFIRMPOPUP_LABEL = "Confirm Bid Awards w/ Popup"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDALLOWNEGATIVEBIDS_LABEL1 = "Allow Negative Bids"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDALLOWNEGATIVEBIDS_LABEL2 = "(People can bid more than they have)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDFIXEDBIDDING_LABEL1 = "Use Fixed Bidding"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDFIXEDBIDDING_LABEL2 = "(Always charges cost from loot table)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDNOTIFYLOWBIDS_LABEL1 = "Notify Low Bidders"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDNOTIFYLOWBIDS_LABEL2 = "(Tell people when they have bid too low)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEAUTOGIVE_LABEL1 = "Auto Give Items"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEAUTOGIVE_LABEL2 = "(Caution! Gives Items Automatically"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLETURNBASE_LABEL1 = "Turn Base DKP"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLETURNBASE_LABEL2 = "Also enables fixed bidding above."
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLESILENTBIDDING_LABEL1 = "Silent Bidding."
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLESILENTBIDDING_LABEL2 = "Doesn't announce who's winning."
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANDROLL_LABEL1 = "Monitor Rolls during Bidding."
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANDROLL_LABEL2 = "Check if you roll for offspec items."
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEALLNEED_LABEL1 = "Enable % for !need"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEALLNEED_LABEL2 = "Enables user defined % for !need"
L.WEBDKP_BIDDINGOPTIONS_FRAME_NEEDDKP_LABEL = "!Need DKP %:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEFIFTYGREED_LABEL1 = "Enable % for !greed"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEFIFTYGREED_LABEL2 = "Enables user defined % for !greed"
L.WEBDKP_BIDDINGOPTIONS_FRAME_GREEDDKP_LABEL = "!Greed DKP %:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEDISABLEBID_LABEL1 = "Disable !bid"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEDISABLEBID_LABEL2 = "Used to disable !bid, forces !main,!off"
--WebDKP_BiddingOptions2_Frame
L.WEBDKP_BIDDINGOPTIONS2_FRAME_INFO1 = "Bidding Options Continued:"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_INFO2 = "Click Icons to Set Multiplier:"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TOGGLEITEMLEVELEQUATION_LABEL = "Enable Item Level Multiplier"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_ITEMLEVELMULT_LABEL = "Value Ex(.01):"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TOGGLESLOTLOCMULT_LABEL = "Enable Slot Location Multiplier"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_HELMBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_NECKBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_SHOULDERSBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_BACKBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_CHESTBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_WRISTBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_HANDSBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_WAISTBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_LEGSBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_FEETBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_FINGERBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TRINKETBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_MAINHANDBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_OFFHANDBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_RANGEDBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_RELICBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_TWOHANDBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_ONEHANDBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_OFFHANDWEAPONBUTTON = "Testing"
L.WEBDKP_BIDDINGOPTIONS2_FRAME_HELDOFFHANDBUTTON = "Testing"
--WebDKP_AnnouncementsOptions_Frame
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO12 = "Announcement Options:"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO13 = "Custom Message - Start Bid"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO14 = "Custom Message - During Bid"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO15 = "Custom Message - End Bid"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO16 = "Custom Message - Start Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO17 = "Custom Message - During Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO18 = "Custom Message - End Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_TOGGLEANNOUNCEMENTS_LABEL = "Disable All Announcments"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITSTARTANNOUNCE_LABEL = "Use $item = Item, $time = Time, $bid = Starting Bid"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITDURINGANNOUNCE_LABEL = "Use $item = Item, $time = Time, $name = Name, $dkp = DKP"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITENDANNOUNCE_LABEL = "Use $item = Item, $name = Name, $dkp = DKP, $totbid = Tot. Bids"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITSROLLANNOUNCE_LABEL = "Use $item = Item, $time = Time"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITROLLANNOUNCE_LABEL = "Use $item = Item, $time = Time, $name = Name, $roll = Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITEROLLANNOUNCE_LABEL = "Use $item = Item, $name = Name, $roll = Roll, $roltot = Tot. Rolls"
--WebDKP_ItemSlotFrame
L.WEBDKP_ITEMSLOTFRAME_TITLE = "main text goes here"
L.WEBDKP_ITEMSLOTFRAME_COST = "Multiplier Value:"
L.WEBDKP_ITEMSLOTFRAME_YES = "Accept"
L.WEBDKP_ITEMSLOTFRAME_NO = "Cancel"
--tab
L.WEBDKP_OPTIONSFRAME_TAB1 = "General"
L.WEBDKP_OPTIONSFRAME_TAB2 = "Bidding"
L.WEBDKP_OPTIONSFRAME_TAB4 = "Bidding Cont."
L.WEBDKP_OPTIONSFRAME_TAB3 = "Announcements"
--Announcments.lua
L.FORMAT_WEBDKP_ITEMAWARD = "WebDKP: $player awarded $item for: $cost dkp."
L.FORMAT_WEBDKP_ITEMAWARDZEROSUM = "WebDKP: $dkp dkp awarded to all players for ZeroSum: $item"
L.FORMAT_WEBDKP_DKPAWARDALL = "WebDKP: $dkp dkp given to all players for: $reason."
L.FORMAT_WEBDKP_DKPAWARDSOME = "WebDKP: $dkp dkp given to selected players for: $reason. \nReceiving players have all been whispered."
L.FORMAT_WEBDKP_BIDSTART = "WebDKP: Bidding has started on $item! $time "
L.FORMAT_WEBDKP_BIDEND = "WebDKP: Bidding has ended for $item The winner was $name who bid $dkp dkp"
L.FORMAT_WEBDKP_BIDENDSILENT = "WebDKP: Bidding has ended for $item"
L.FORMAT_WEBDKP_ROLLEND = "WebDKP: Rolling has ended for $item. $name was the high roller with a $roll"
L.FORMAT_WEBDKP_TIMEDAWARD = "WebDKP: $minutes Minute Timed Award of $dkp dkp Given"
L.FORMAT_WEBDKP_BOSSAWARDNUM = "WebDKP: Great Job! A Boss Award of $dkp Has Been Given"
L.FORMAT_WEBDKP_SENDWHISPER_PLUS = "You have been rewarded "
L.FORMAT_WEBDKP_SENDWHISPER_REDUCE = "You have been deducted "

--AutoFill.lua
L.FORMAT_FIND_ITEM_LOOT = "receives loot:"

--https://wow.gamepedia.com/DungeonEncounterID
--https://wow.gamepedia.com/InstanceID
L.BOSS_MAP = {
    --"Molten Core"
    [409] = "BossDKPMCAndOLValue",
    --"Onyxia's Lair"
    [249] = "BossDKPMCAndOLValue",
    --"Blackwing Lair"
    [469] = "BossDKPBWLValue",
    --"Temple of Ahn'Qiraj"
    [531] = "BossDKPTAQValue",
    --"Naxxramas"
    [533] = "BossDKPNAXXValue"
}

--WebDKP.lua
L.IgnoreItems1 = "Void Crystal"
L.IgnoreItems2 = "Elementium Ore"
L.Multipleplayers = "Multiple"

--Announcments.lua
L.AnnounceBidstarting = "To place a bid say !bid <value> in a raid/party/whisper. "
L.Announceinstructions = "(ex: !bid 50)"
L.BidFixedBidding = "To place a bid say !need in a raid/party/whisper."
L.startingBidText = "Bidding starts at "
L.time_second = "s)"
L.Userdefined = "User Defined"
L.startingBidvalue = "No Starting Bid"
L.TimeFlag = "Time remaining:"
L.Rollsstart1 = "Rolling has started for $item. Please type /roll to roll."
L.Rollsstart2 = "Rolling has started for $item. Please type /roll to roll. Time Remaining: $time"
L.NOone = "no one"
L.AnnounceTop3 = "WebDKP: The top three bidders were:"
L.AnnounceTop3BID = " bidding "

--AutoFill.lua
L.ShowAwardtext = "Award "
L.ShowAwardtext2 = " DKP? \r\n (Enter DKP below, positive numbers only, % values work (50%)"
L.Noinput_Print = "No value was entered so the DKP defaulted to 0."
L.Noplayer_Print = "No player was selected to award. Award NOT made."

--Awards.lua
L.ItemName_Print = "You must enter an item name."
L.Noreasonspecified = "Not Specified"
L.RewardPoints_Print = "You must enter points to award."
L.Nochoice_Print = "No players were selected. Award NOT made."
L.reasonZerosum = "ZeroSum: "
L.reasondecay = "Decay_"
L.hasapplieddecay = "Decay has been applied."

--Bidding.lua
L.triggerBID = "!bid "
L.triggerBID2 = "!bid"
L.triggerSH = "!bidall"
L.triggerMAINTLENT = "!main"
L.triggerOFFTLENT = "!off"
L.triggerBIDDINGTOSTART = "!startbid"
L.triggerBIDDINGTOSTOP = "!stopbid"
L.triggerNEED = "!need"
L.triggerGREED = "!greed"
L.framestopbinding = "Stop Bidding"
L.framestartbinding = "Start the Bidding!"
L.framestartrolling = "Rolling Has Started!"
L.framestoprolling = "Stop Rolling"
L.framelefttimetext = "Time Left: "
L.framelefttimesecondtext = "s"
L.defaultBIPmsg = "WebDKP: $name is winning with a high bid of $dkp. There are $time seconds remaining for bidding on $item!"
L.defaultSBIPmsg = "WebDKP: There are $time seconds remaining for bidding on $item!"
L.defaultRIPmsg = "WebDKP: The highest roller is $name with a $roll. There are $time seconds remaining to roll on $item."
L.SendAnnouncement = "Bidding Has Started!"
L.ShowAwardtextfor = " for "
L.ShowAwardtext3 = "? |cFFFF0000(Item not in loot table)|r"
L.ShowAwardtext4 = " dkp? (From LootTable or Item Level Mult)"
L.ShowAwardtext5 = " dkp? (Percents work. Ex:50%)"
L.SendWhisper1 = "You did not bid properly, use !bid #"
L.SendWhisper2 = "There is no bid in progress"
L.SendWhisper3 = "You did not specify a bid amount - bid not accepted"
L.SendWhisper4 = "Bid not accepted. The minimum bid is "
L.SendWhisper5 = "Bid not accepted. You must type !need"
L.SendWhisper6 = "Bid not accepted. Please use !main value or !off value"
L.SendWhisper7 = "Bid for "
L.SendWhisper8 = " dkp accepted"
L.SendWhisper9 = "Bid not accepted, you don't have enough DKP. The minimum bid is "
L.SendWhisper10 = "Bid not accepted. You must type !need"
L.SendWhisper11 = "Your mainspec need has been accepted."
L.SendWhisper12 = "Mainspec Bid for "
L.SendWhisper13 = "Bid not accepted, you don't have enough DKP. The minimum bid is "
L.SendWhisper14 = "Your offspec need has been accepted."
L.SendWhisper15 = "Offspec Bid for "
L.SendWhisper16 = "Bid not accepted. You must type !greed"
L.SendWhisper17 = "There is already a bid in progress - you can't start another bid until the first one is finished"
L.SendWhisper18 = "You must specify an item to bid on. Example: !startbid [Giantstalker's Helm]"
L.SendWhisper19 = "Bid Rejected - you cannot bid more than you have."
L.SendWhisper20 = "Your maximum bid is "
L.SendWhisper21 = "Bid Rejected - The minimum DKP to win this item is "
L.SendWhisper22 = "You are the current high bidder"
L.SendWhisper23 = "You are NOT the high bidder. The current high bid is  "
L.startrolling_Print = "You must enter an item to roll on."

--Options.lua
L.itemquality = "Gray Items"
L.itemquality2 = "White Items"
L.itemquality3 = "Green Items"
L.itemquality4 = "Blue Items"
L.itemquality5 = "Purple Items"
L.itemquality6 = "Orange Items"
L.Bossrewardenable_Print = "Auto Boss awards Enabled"
L.Bossrewarddisable_Print = "Auto Boss awards Disabled"

--Standby.lua
L.Standby_Print = "You must enter a name or select a player to add or remove them to the standby list."
L.Standby_Print2 = "This person doesn't exist in your table."
L.Standby_SendWhisper = "You are now listed as a standby player"
L.Standby_SendWhisper2 = "You have been removed as a standby player"

--TimedAward.lua
L.AwardBossDKPIgnoreZero_Print = "%s:%s Auto BossKill Areward DKP for 0, ignored"
L.AddDKPReason_BOSS = "Auto Award Boss Kill: "
L.StartStopButtonText = "Start"
L.StartStopButtonText2 = "Stop"
L.ReasonTimedAward = "Timed Auto Award"
--WhisperDKP.lua
L.WhisperDKP1 = "You have no DKP history"
--L.WhisperDKP2 = "更多明细请微信搜索小程序'webdkp'查看哦!"
L.WhisperDKP3 = "Current DKP : "
L.WhisperDKP4 = "You've attended : "
L.WhisperDKP5 = " out of "
L.WhisperDKP6 = " raids. Your percent made is "
L.WhisperDKP7 = "You currently show no raid data."
L.triggerWhisperDKP = "!dkp"
L.triggerWhisperDKP1 = "!list"
L.triggerWhisperDKP2 = "!standby add"
L.triggerWhisperDKP3 = "!standby del"
L.triggerWhisperDKP4 = "!attendance"

L.DB_DUNGEON_ENCOUNTER = {
    --"Molten Core"
    [663] = "Lucifron",
    [664] = "Magmadar",
    [665] = "Gehennas",
    [666] = "Garr",
    [667] = "Shazzrah",
    [668] = "Baron Geddon",
    [669] = "Sulfuron Harbinger",
    [670] = "Golemagg the Incinerator",
    [671] = "Majordomo Executus",
    [672] = "Ragnaros",
    --"Onyxia's Lair"
    [1084] = "Onyxia",
    --"Blackwing Lair"
    [610] = "Razorgore the Untamed",
    [611] = "Vaelastrasz the Corrupt",
    [612] = "Broodlord Lashlayer",
    [613] = "Firemaw",
    [614] = "Ebonroc",
    [615] = "Flamegor",
    [616] = "Chromaggus",
    [617] = "Nefarian",
    --"Temple of Ahn'Qiraj"
    [709] = "The Prophet Skeram",
    [710] = "Silithid Royalty",
    [711] = "Battleguard Sartura",
    [712] = "Fankriss the Unyielding",
    [713] = "Viscidus",
    [714] = "Princess Huhuran",
    [715] = "Twin Emperors",
    [716] = "Ouro",
    [717] = "C'thun",
    --"Naxxramas"
    [1107] = "Anub'Rekhan",
    [1108] = "Gluth",
    [1109] = "Gothik the Harvester",
    [1110] = "Grand Widow Faerlina",
    [1111] = "Grobbulus",
    [1112] = "Heigan the Unclean",
    [1113] = "Instructor Razuvious",
    [1114] = "Kel'Thuzad",
    [1115] = "Loatheb",
    [1116] = "Maexxna",
    [1117] = "Noth the Plaguebringer",
    [1118] = "Patchwerk",
    [1119] = "Sapphiron",
    [1120] = "Thaddius",
    [1121] = "The Four Horsemen",
}