---
--- 由60addons創建並漢化(https://60addons.com)

if (GetLocale() ~= "zhTW") then
    return
end

local L = WebDKP.translations

--中文職業簡稱
L.CLASS_ALIAS_TO_ENG_MAP["LR"] = "hunter"
L.CLASS_ALIAS_TO_ENG_MAP["QS"] = "paladin"
L.CLASS_ALIAS_TO_ENG_MAP["ZS"] = "warrior"
L.CLASS_ALIAS_TO_ENG_MAP["FS"] = "mage"
L.CLASS_ALIAS_TO_ENG_MAP["SS"] = "warlock"
L.CLASS_ALIAS_TO_ENG_MAP["SM"] = "shaman"
L.CLASS_ALIAS_TO_ENG_MAP["DZ"] = "rogue"
L.CLASS_ALIAS_TO_ENG_MAP["MS"] = "priest"
L.CLASS_ALIAS_TO_ENG_MAP["XD"] = "druid"

--小地圖右鍵

L.WEBDKP_MINIMAPDROPDOWN_OPTIONS = "設置"
L.WEBDKP_MINIMAPDROPDOWN_HELP = "新手幫助"

--DKP表標頭
L.WEBDKP_HEADER = "DKP 表:"
L.WEBDKP_FRAME_NAME_COLUMN = "名字"
L.WEBDKP_FRAME_CLASS_COLUMN = "職業"
L.WEBDKP_FRAME_DKP_COLUMN = "DKP"
L.WEBDKP_FRAME_GUILDRANK_COLUMN = "狀態"

--DKP表選項卡
L.TAB_FILTER = "過濾"
L.TAB_AWARD_DKP = "獎懲"
L.TAB_AWARD_ITEM = "物品"
L.TAB_STANDBY = "替補"

--DKP表過濾項
L.FILTER_HEADER = "過濾:"
L.FILTER_CLASS_WARLOCK = "|cff9482C9術士|r"
L.FILTER_CLASS_WARRIOR = "|cffC79C6E戰士|r"
L.FILTER_CLASS_HUNTER = "|cffABD473獵人|r"
L.FILTER_CLASS_MAGE = "|cff69CCF0法師|r"
L.FILTER_CLASS_PRIEST = "|cffFFFFFF牧師|r"
L.FILTER_CLASS_DRUID = "|cffFF7D0A德魯伊|r"
L.FILTER_CLASS_PALADIN = "|cffF58CBA聖騎士|r"
L.FILTER_CLASS_SHAMAN = "|cff0099FF薩滿祭司|r"
L.FILTER_CLASS_ROGUE = "|cffFFF569潛行者|r"

L.FILTER_CLASS_CASTERS = "遠程法術"
L.FILTER_CLASS_MELEE = "物理近戰"
L.FILTER_CLASS_HEALER = "治療"
L.FILTER_CLASS_CHAIN = "鎖甲"
L.FILTER_CLASS_CLOTH = "布甲"
L.FILTER_CLASS_LEATHER = "皮甲"
L.FILTER_CLASS_PLATE = "板甲"

L.FILTER_CHECK_ALL = "選取所有"
L.FILTER_UNCHECK_ALL = "取消所有"
L.FILTER_PLAYERS_IN_GROUP = "團內"
L.FILTER_STANDBY_PLAYERS = "替補"
L.FILTER_OTHERS_PLAYERS = "其他"

L.DKP_TABLE_SELECT_ALL = "選取所有"
L.DKP_TABLE_DESELECT_ALL = "取消所有"
L.DKP_TABLE_SAVE_LOG = "|cFF0dea38>保存數據文檔<|r"
L.DKP_TABLE_Refresh = "刷新"

--獎懲選項卡
L.AWARD_DKP_HEADER = "獎懲DKP:"
L.AWARD_DKP_INFO1 = "先選取左側的玩家\n然後輸入DKP獎懲"
L.AWARD_DKP_DECAY_HEADER = "DKP百分比衰減:\n(僅適用於實施了\nDKP衰減制度的公會)"
L.AWARD_DKP_INFO3 = ""
L.AWARD_DKP_REASON_LABEL = "原因:"
L.AWARD_DKP_POINTS_LABEL = "點數: (使用負數為扣分)"
L.AWARD_DKP_AWARD_POINTS = "獎懲!"
L.AWARD_DKP_DECAY_LABEL = "衰減值:如(|cFF0dea38.4|r) 為衰減40%"
L.AWARD_DKP_DECAY_BUTTON = "衰減"

--獎懲物品選項卡
L.AWARD_ITEM_HEADER = "獎懲物品:"
L.AWARD_ITEM_INFO1 = "左邊選取要獎懲的玩家\n 下放輸入DKP資訊"
L.AWARD_ITEM_ITEM_NAME_LABEL = "物品名:"
L.AWARD_ITEM_ITEM_COST_LABEL = "物品DKP: (只允許正數)"
L.AWARD_ITEM_ITEM_COST_LABEL2 = ""
L.AWARD_ITEM_AWARD_ITEM = "獎懲!"

--替補選項卡
L.STANDBY_HEADER = "替補玩家:"
L.STANDBY_INFO1 = "替補人員輸入命令:|cFF0dea38我要替補|r\n或者:|cFF0dea38退出替補|r"
L.STANDBY_ADD_STANDBY_LABEL = "玩家名:"
L.STANDBY_ADD_TO_STANDBY = "添加"
L.STANDBY_DEL_STANDBY = "刪除"
L.STANDBY_RESET_STANDBY = "重置"
L.STANDBY_ENABLE_STANDBY_ZEROSUM = "為替補玩家啟用零和規則"
L.STANDBY_ENABLE_STANDBY_TIMED = "為替補玩家啟用時間分獎勵"

--競拍頁
L.BID_TITLE = "WebDKP 競拍"
L.BID_ITEM_LABEL = "物品:"
L.BID_STARTING_BID_LABEL = "起始DKP:"
L.BID_TIME_LABEL = "競拍/Roll時間:"
L.BID_TIME_HINT = "(秒 - 0為無限制)"
L.BID_BID_BUTTON = "開始競拍!"
L.BID_ROLL_BUTTON = "開始Roll!"
L.BID_TOP3_BUTTON = "通知競拍前3名"
L.BIDCountdown = "競拍倒數: "
L.BIDCountdowncancel = "取消倒數"
L.Fiveseconds = "倒數5秒"
L.BID_TABLE_HEADER = "收到的競拍/Rolls:"
L.BID_TABLE_COLUMN_NAME_LABEL = "名字"
L.BID_TABLE_COLUMN_BID_LABEL = "競拍"
L.BID_TABLE_COLUMN_DKP_LABEL = "DKP"
L.BID_TABLE_COLUMN_POST_LABEL = "DKP - 競拍"
L.BID_TABLE_COLUMN_ROLL_LABEL = "Rolls"
L.BID_TABLE_COLUMN_SPEC_LABEL = "主/副"
L.BID_TABLE_COLUMN_GUILD_RANK_LABEL = "公會會階"
L.BID_AWARD = "獎懲裝備"
L.FORMAT_MSG_ROLLING_PATTERN = "(.+)擲出(%d+)%（(%d+)%-(%d+)%）"


--時間分頁
L.WEBDKP_TIMEDAWARDFRAME_TITLE = "時間分獎勵"
L.WEBDKP_TIMEDAWARDFRAME_TEXT = "時間分獎勵允許你為 DKP 設置一個時間自動獎勵分"
L.WEBDKP_TIMEDAWARDFRAME_DKP_LABEL = "DKP:"
L.WEBDKP_TIMEDAWARDFRAME_TIME_LABEL = "時間:"
L.WEBDKP_TIMEDAWARDFRAME_TIME_HINT = "(分鐘)"
L.WEBDKP_TIMEDAWARDFRAME_LOOPTIMER_LABEL = "重複獎勵:"
L.WEBDKP_TIMEDAWARDFRAME_RESETBUTTON = "重置"
L.STANDBY_RESET_STANDBY_LABEL = "重置所有替補玩家:"
L.WEBDKP_TIMEDAWARDFRAME_STARTSTOPBUTTON = "開始"
L.WEBDKP_TIMEDAWARDFRAME_MINIBUTTON = "迷你計時器"

--設置頁
L.WEBDKP_OPTIONSFRAME_TITLE = "WebDKP 設置"
--WebDKP_GeneralOptions_Frame
L.WEBDKP_GENERALOPTIONS_FRAME_TITLE = "一般設置:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO1 = "自動填充物品設置:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO2 = "零和DKP:"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO3 = "自動Boss擊殺獎勵:(單個Boss分)"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO4 = "啟用/禁用WebDKP"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO5 = "啟用或禁用Alt+左鍵，彈出競價窗口"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO6 = "非隊伍/團隊玩家遮罩私聊"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO7 = "指定一個DKP封頂(任何到了該DKP的玩家將無法獲得DKP)"
L.WEBDKP_GENERALOPTIONS_FRAME_INFO8 = "EP / GP:"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAUTOFILLENABLED_LABEL = "自動填充物品名"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAUTOAWARDENABLED_LABEL = "自動彈框啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEZEROSUMENABLED_LABEL = "零和模式啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEAWARDBOSSDKP_LABEL = "啟用/禁用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEALTCLICK_LABEL = "Alt+左鍵 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEIGNWHISPERS_LABEL = "遮罩 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEDKPCAP_LABEL = "DKP封頂 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_DKPCAPLIMIT_LABEL = "封頂限制:"
L.WEBDKP_GENERALOPTIONS_FRAME_BOSSDKP_LABEL = "DKP 數:"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEENABLED_LABEL = "WebDKP 啟用"
L.WEBDKP_GENERALOPTIONS_FRAME_TOGGLEENABLED_LABEL = "WebDKP 啟用"
--WebDKP_BiddingOptions_Frame
L.WEBDKP_BIDDINGOPTIONS_FRAME_INFO1 = "競拍選項:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANNOUNCERAID_LABEL = "通告在團隊警報"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDCONFIRMPOPUP_LABEL = "配置競拍獎懲彈出"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDALLOWNEGATIVEBIDS_LABEL1 = "允許負DKP競拍"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDALLOWNEGATIVEBIDS_LABEL2 = "(允許人們負數競拍)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDFIXEDBIDDING_LABEL1 = "使用固定DKP分數競拍"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDFIXEDBIDDING_LABEL2 = "(從固定DKP列表中決定DKP分數)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDNOTIFYLOWBIDS_LABEL1 = "當DKP低了通知競拍者"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDNOTIFYLOWBIDS_LABEL2 = "(告訴他們現在你不是最高競拍者了)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEAUTOGIVE_LABEL1 = "自動給予裝備"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEAUTOGIVE_LABEL2 = "(謹慎使用！自動給予裝備)"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLETURNBASE_LABEL1 = "all in(梭哈)DKP"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLETURNBASE_LABEL2 = "同時啟用在固定競拍上"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLESILENTBIDDING_LABEL1 = "靜默"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLESILENTBIDDING_LABEL2 = "不會宣佈誰贏了"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANDROLL_LABEL1 = "競拍中監視Roll"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEBIDANDROLL_LABEL2 = "專為副天賦裝備檢查"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEALLNEED_LABEL1 = "啟用需求百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEALLNEED_LABEL2 = "為'需求'啟用用戶定義的百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_NEEDDKP_LABEL = "'需求' DKP %:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEFIFTYGREED_LABEL1 = "啟用貪婪百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEFIFTYGREED_LABEL2 = "為'貪婪'啟用用戶定義的百分比"
L.WEBDKP_BIDDINGOPTIONS_FRAME_GREEDDKP_LABEL = "'貪婪' DKP %:"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEDISABLEBID_LABEL1 = "禁用'出價'命令"
L.WEBDKP_BIDDINGOPTIONS_FRAME_TOGGLEDISABLEBID_LABEL2 = "用戶禁用'出價', 強制使用'主天賦''副天賦'命令"
--WebDKP_AnnouncementsOptions_Frame
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO12 = "通告選項:"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO13 = "自定義資訊 - 開始競拍"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO14 = "自定義資訊 - 競拍期間"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO15 = "自定義資訊 - 結束競拍"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO16 = "自定義資訊 - 開始Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO17 = "自定義資訊 - Roll期間"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_INFO18 = "自定義資訊 - 結束Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_TOGGLEANNOUNCEMENTS_LABEL = "禁用所有公告"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITSTARTANNOUNCE_LABEL = "$item = 物品, $time = 時間, $bid = 起始DKP"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITDURINGANNOUNCE_LABEL = "$item = 物品, $time = 時間, $name = 名字, $dkp = DKP"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITENDANNOUNCE_LABEL = "$item = 物品, $name = 名字, $dkp = DKP, $totbid = Tot. Bids"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITSROLLANNOUNCE_LABEL = "$item = 物品, $time = 時間"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITROLLANNOUNCE_LABEL = "$item = 物品, $time = 時間, $name = 名字, $roll = Roll"
L.WEBDKP_ANNOUNCEMENTSOPTIONS_FRAME_EDITEROLLANNOUNCE_LABEL = "$item = 物品, $name = 名字, $roll = Roll, $roltot = Tot. Rolls"

--設置頁選項卡
L.WEBDKP_OPTIONSFRAME_TAB1 = "一般"
L.WEBDKP_OPTIONSFRAME_TAB2 = "競拍"
L.WEBDKP_OPTIONSFRAME_TAB3 = "公告"

--Announcments.lua
L.FORMAT_WEBDKP_ITEMAWARD = "WebDKP: $player 給予裝備: $item ,被扣了: $cost DKP"
L.FORMAT_WEBDKP_ITEMAWARDZEROSUM = "WebDKP: $dkp 點DKP被獎懲給所有玩家, 零和規則: $item"
L.FORMAT_WEBDKP_DKPAWARDALL = "WebDKP: $dkp 點DKP給予了所有玩家, 原因: $reason."
L.FORMAT_WEBDKP_DKPAWARDSOME = "WebDKP: $dkp 點DKP給予了所有被選擇的玩家, 原因: $reason \n接收到的玩家都被密語了"
L.FORMAT_WEBDKP_BIDSTART = "WebDKP: 競拍已開始 $item! $time "
L.FORMAT_WEBDKP_BIDEND = "WebDKP: $item 競拍已結束, 勝利者為 $name , $dkp dkp"
L.FORMAT_WEBDKP_BIDENDSILENT = "WebDKP: 競拍已結束 $item"
L.FORMAT_WEBDKP_ROLLEND = "WebDKP: Roll點已結束 $item , $name 是最高點, 為 $roll"
L.FORMAT_WEBDKP_TIMEDAWARD = "WebDKP: $minutes 分鐘獎勵分, 已給予 $dkp dkp"
L.FORMAT_WEBDKP_BOSSAWARDNUM = "WebDKP: 幹得漂亮! Boss獎勵分: $dkp 已自動給予"
L.FORMAT_WEBDKP_SENDWHISPER_PLUS = "你被獎勵了 "
L.FORMAT_WEBDKP_SENDWHISPER_REDUCE = "你被扣除了 "

--AutoFill.lua
L.FORMAT_FIND_ITEM_LOOT = "獲得了物品"

--WebDKP.lua
L.IgnoreItems1 = "連結水晶"
L.IgnoreItems2 = "源質礦石"
L.Multipleplayers = "多個玩家"

L.AwardFrameTitle = "Award ZeddZorandor thisisareallylongitemname for 10000 dkp?"
L.AwardFrameTitleYES = "是"
L.AwardFrameTitleNO = "不"
L.BidConfirmFrameCost = "DKP:"
L.BidConfirmFrameYes = "是"
L.BidConfirmFrameNo = "不"
L.CharRaidInfoFrameTitle = "角色出勤日誌"
L.CharRaidInfoFrameHeaderLogTable = "僅顯示在本地,網站無任何相關數據,出勤查詢命令:|cFF0dea38出勤|r"
L.CharRaidInfoFrameHeaderAttended = "參與過的Raid:"
L.CharRaidInfoFrameFilterDaysLabel = "輸入開始日期以篩選當前日期之前的數據:(如:11-10-2019)"
L.CharRaidInfoFrameCharRaidNameLabel = "角色名"
L.CharRaidInfoFrameCharRaidAttendedLabel = "出席過"
L.CharRaidInfoFrameCharRaidPercentLabel = "百分比"
L.CharRaidInfoFrameCharRaidTotRaidsLabel = "總次數"
L.CharRaidInfoFrameCharRaidLocationLabel = "地點"
L.CharRaidInfoFrameCharRaidDateLabel = "日期"
L.CharRaidInfoFrameRemChar = "刪除角色"
L.CharRaidInfoFrameInGroupLabel = "只顯示當前團隊中的用戶"
L.CharRaidInfoFrameFilterDateLabel = "開始日期:"
L.CharRaidInfoFrameApplyFilterDateLabel = "應用過濾"
L.FrameZoneColumn = "區域"
L.FrameWebsiteLabel = "http://webdkp.wowcat.net/"
L.FrameAnnounceDKPLimitToGroupText = "僅團隊內"
L.FrameAnnounceDKP = "發送職業DKP"
L.FrameSelectAllText = "|cFF33FF00全選|r"
L.FrameDeselectAllText = "取消全選"
L.HelpFrameTitle = "WebDKP 幫助"
L.Help_DropDownLabel = "幫助類別:"
L.LogFrameTitle = "WebDKP 獎懲日誌"
L.LogFrameHeaderLogTable = "本次遊戲獎懲日誌表:(同步後將會清空)"
L.LogFrameHeaderAwardedTo = "名字:"
L.LogFrameDirChar = "添加或刪除一個角色"
L.LogFrameDirFilter = "查詢角色"
L.LogFrameAwardedtoLabel = "名字"
L.LogFrameAmountLabel = "DKP"
L.LogFrameReasonLabel = "原因"
L.LogFrameDateLabel = "日期"
L.LogFrameCharChangeLabel = "名字:"
L.LogFrameDelChar = "刪除"
L.LogFrameAddChar = "添加"
L.LogFramePlayerFilterLabel = "名字:"
L.LogFramePlayerFilterOK = "查詢"
L.LogFramePlayerFilterCancel = "取消"
L.LogFrameSaveLog = "|cFF0dea38>保存數據文檔<|r"
L.GeneralOptions_FrameAutofillDropDownLabel = "自動彈框品質"
L.GeneralOptions_FrameToggleAwardBossDKPIgnoreZeroLabel = "忽略0分"
L.GeneralOptions_FrameBossDKPMCAndOLLabel = "MC|ONY:"
L.GeneralOptions_FrameBossDKPBWLLabel = "BWL:"
L.GeneralOptions_FrameBossDKPTAQLabel = "TAQ:"
L.GeneralOptions_FrameBossDKPNAXXLabel = "NAXX:"
L.RaidInfoFrameTitle = "WebDKP 團隊日誌"
L.RaidInfoFrameHeaderLog = "本地團隊日誌表:(手動功能,僅在本地顯示,網站無任何相關數據)"
L.RaidInfoFrameHeaderAttended = "參與者:"
L.RaidInfoFrameHeaderDirTime = "如果忘記結束Raid，請在此處輸入總的Raid時間（以小時為單位）"
L.RaidInfoFrameHeaderDirChar = "你可以在此處添加或刪除Raid出勤的角色"
L.RaidInfoFrameRaidLocationLabel = "Raid 地點"
L.RaidInfoFramedateLabel = "日期"
L.RaidInfoFramestartTimeLabel = "開始時間"
L.RaidInfoFrameendTimeLabel = "結束時間"
L.RaidInfoFrametotaltimeLabel = "總時間"
L.RaidInfoFrameStartRaid = "開始"
L.RaidInfoFrameStopRaid = "結束"
L.RaidInfoFrameDeleteRaid = "刪除"
L.RaidInfoFrameEndTimeLabel = "時間（小時）:"
L.RaidInfoFrameAdjustTime = "調整時間"
L.RaidInfoFrameCharChangeLabel = "玩家名:"
L.RaidInfoFrameAddChar = "添加玩家"
L.RaidInfoFrameDelChar = "刪除玩家"
L.SynchFrameTitle = "WebDKP - 遊戲內同步"
L.SynchFrameText = "遊戲內同步允許用戶在遊戲中共享數據,雙方輸入對方名字,相同密碼,一個人按同步"
L.SynchFrameUsers = "接受的用戶-您將接受來自的以下列表的人的數據"
L.SynchFrameNameLabel = "名字"
L.SynchFrameEnableSynchLabel = "啟用(勾選), 禁用(不勾選)"
L.SynchFramePasswordLabel = "密碼:"
L.SynchFrameSynchFromLabel = "與玩家同步:"
L.SynchFrameSynchronize = "僅同步DKP"
L.SynchFrameSynchAll = "同步DKP和日誌"
L.SynchFrameAddSynchUserLabel = "添加或刪除接受的用戶"
L.SynchFrameAddUser = "添加"
L.SynchFrameDelUser = "刪除"
L.TimedAward_MiniFrameTimeLeft = "00:00"
L.WinTabFrameTab1 = "DKP"
L.WinTabFrameTab2 = "競拍"
L.WinTabFrameTab3 = "時間分"
L.WinTabFrameTab4 = "同步"
L.WinTabFrameTab5 = "日誌"
L.WinTabFrameTab6 = "Raid"
L.WinTabFrameTab7 = "出勤"

--Announcments.lua
L.AnnounceBidstarting = "如果要出價,就在團隊/小隊/私聊裏輸入: 出價 分數 "
L.Announceinstructions = "(如: 出價 50)，或者直接輸入分數！"
L.BidFixedBidding = "如果要出價,就在團隊/小隊/私聊裏輸入：需求"
L.startingBidText = "拍賣底價: "
L.time_second = "秒)"
L.Userdefined = "用戶自定義"
L.startingBidvalue = "無底價"
L.TimeFlag = "剩餘時間:"
L.Rollsstart1 = "Roll點開始： $item 請輸入 /roll"
L.Rollsstart2 = "Roll點開始： $item 請輸入 /roll 剩餘時間: $time"
L.NOone = "無人"
L.AnnounceTop3 = "WebDKP: 前三名的競拍者是:"
L.AnnounceTop3BID = " 出價: "

--AutoFill.lua
L.ShowAwardtext = "授予 "
L.ShowAwardtext2 = " ? \r\n (在下面輸入DKP，僅限正數)"
L.Noinput_Print = "未輸入值，因此dkp默認為0"
L.Noplayer_Print = "沒有選擇要授予的玩家"

--Awards.lua
L.ItemName_Print = "必須輸入物品名稱"
L.Noreasonspecified = "未指定"
L.RewardPoints_Print = "你必須輸入獎勵點數"
L.Nochoice_Print = "未選擇任何玩家"
L.reasonZerosum = "零和: "
L.reasondecay = "衰減_"
L.hasapplieddecay = "已應用衰減"

--Bidding.lua
L.triggerBID = "出價 "
L.triggerBID2 = "出價"
L.triggerSH = "sh"
L.triggerMAINTLENT = "主天賦"
L.triggerOFFTLENT = "副天賦"
L.triggerBIDDINGTOSTART = "開拍"
L.triggerBIDDINGTOSTOP = "停拍"
L.triggerNEED = "需求"
L.triggerGREED = "貪婪"
L.framestopbinding = "停止競拍"
L.framestartbinding = "開始競拍!"
L.framestartrolling = "Roll點開始!"
L.framestoprolling = "停止Roll點!"
L.framelefttimetext = "剩餘時間: "
L.framelefttimesecondtext = "秒"
L.defaultBIPmsg = "WebDKP: $name 以 $dkp 的高價獲得競拍. 還有 $time 秒可以競拍 $item!"
L.defaultSBIPmsg = "WebDKP: 還剩 $time 秒， $item!"
L.defaultRIPmsg = "WebDKP: $name 以 $roll 點，為最高Roll點. 還有 $time 秒可以Roll $item"
L.SendAnnouncement = "競拍開始!"
L.ShowAwardtextfor = " 為： "
L.ShowAwardtext3 = "? |cFFFF0000(物品不在戰利品表中)|r"
L.ShowAwardtext4 = " dkp?(取自戰利品列表)"
L.ShowAwardtext5 = " dkp? (百分比，如：50%)"
L.SendWhisper1 = "你出價不當, 輸入'出價 分數'，或者直接輸入分數"
L.SendWhisper2 = "沒有正在進行的競拍"
L.SendWhisper3 = "你沒有指定競拍金額"
L.SendWhisper4 = "競拍不接受. 最低出價是 "
L.SendWhisper5 = "因為DKP管理者啟用了固定分競拍，所以競拍不接受，你必須輸入'需求'"
L.SendWhisper6 = "因為DKP管理者禁用了“出價”命令，所以競拍不接受. 請輸入 ‘主天賦’ 或者 ‘副天賦’"
L.SendWhisper7 = "競拍： "
L.SendWhisper8 = " dkp ，已接受"
L.SendWhisper9 = "競拍不接受, 你沒有足夠的 DKP. 最低出價是 "
L.SendWhisper10 = "競拍不接受. 你必須輸入'需求'"
L.SendWhisper11 = "你的主天賦需求已經被接受!"
L.SendWhisper12 = "主天賦競拍: "
L.SendWhisper13 = "競拍不接受, 你沒有足夠的 DKP. 最低競拍是: "
L.SendWhisper14 = "你的副天賦需求已被接受."
L.SendWhisper15 = "副天賦競拍: "
L.SendWhisper16 = "競拍不接受. 你必須輸入'貪婪'"
L.SendWhisper17 = "已經有一個競拍在進行中-你不能開始另一個競拍"
L.SendWhisper18 = "必須指定要競拍的物品. 如: 開拍 [龍牙]"
L.SendWhisper19 = "競拍被拒絕 - 你不能出價超過你當前DKP"
L.SendWhisper20 = "你的最高出價是 "
L.SendWhisper21 = "競拍被拒絕 - 贏得此物品的最低dkp是 "
L.SendWhisper22 = "你是目前出價最高的人"
L.SendWhisper23 = "你不是出價高的人. 目前的最高價是  "
L.SendWhisper24 = "競拍已收到!"
L.startrolling_Print = "你必須輸入一個裝備才能開始ROll"
L.showhandannounce = " Show hand了他全部的DKP: "

--Options.lua
L.itemquality = "灰色物品"
L.itemquality2 = "白色物品"
L.itemquality3 = "綠色物品"
L.itemquality4 = "藍色物品"
L.itemquality5 = "紫色物品"
L.itemquality6 = "橙色物品"
L.Bossrewardenable_Print = "自動Boss擊殺獎勵已啟用"
L.Bossrewarddisable_Print = "自動Boss擊殺獎勵已禁用"

--Standby.lua
L.Standby_Print = "你必須輸入一個名字或選擇一個玩家才能將其添加或刪除到替補列表中"
L.Standby_Print2 = "此玩家不在你的替補名單上!"
L.Standby_SendWhisper = "你現在被列為替補玩家!請遵守本公會替補規則!"
L.Standby_SendWhisper2 = "你已從替補名單上被移除!"

--TimedAward.lua
L.AwardBossDKPIgnoreZero_Print = "%s:%s 自動擊殺增加的dkp為0，已忽略"
L.AddDKPReason_BOSS = "自動Boss擊殺獎勵: "
L.StartStopButtonText = "開始"
L.StartStopButtonText2 = "停止"
L.ReasonTimedAward = "時間分自動獎勵"
L.FrameToggleAwardBossDKP_Include_StandbyLabel = "包含替補"
--WhisperDKP.lua
L.WhisperDKP1 = "你沒有DKP,查不到你的DKP歷史記錄"
L.WhisperDKP2 = "更多明細請微信搜索小程式'webdkp'查看哦!"
L.WhisperDKP3 = "當前DKP: "
L.WhisperDKP4 = "你出勤過 : "
L.WhisperDKP5 = "次團本,總計: "
L.WhisperDKP6 = " 次團本. 你的出勤百分比是 "
L.WhisperDKP7 = "你當前沒有參與過團隊/團本"
L.triggerWhisperDKP = "mydkp"
L.triggerWhisperDKP1 = "查詢"
L.triggerWhisperDKP2 = "我要替補"
L.triggerWhisperDKP3 = "退出替補"
L.triggerWhisperDKP4 = "出勤"