local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "esMX")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "Autoposicionar la barra de lanzamiento"
L["AUTO_POS_BAR_TOOLTIP"] = [=[Cuando está habilitado, posicionará automáticamente la barra de lanzamiento en función de la cantidad de beneficios que se muestran en el marco de la unidad, etc.
No funciona con marcos de unidades de terceros.]=]
L["BORDER_COLOR"] = "Seleccionar Color del Borde"
L["BORDERSHIELD"] = "Mostrar Escudo de Borde Ininterrumpible"
L["BORDERSHIELD_TOOLTIP"] = "Muestra un escudo alrededor de la barra de lanzamiento cuando un lanzamiento no puede ser interrumpido. La desactivación de esta opción seguirá mostrando un color de fondo gris en los lanzamientos ininterrumpibles.|cffffff00Puede hacer clic en el botón \"Alternar barra de lanzamiento de prueba\" mientras mantiene presionadas las teclas modificadoras como SHIFT o CTRL para probar la barra de cast con el escudo de borde que se muestra.|r"
L["CAST_BORDER"] = "Seleccionar Textura del Borde"
L["CAST_BORDER_TOOLTIP"] = "Selecciona la textura utilizada para el borde de la barra de lanzamiento."
L["CAST_FONT"] = "Seleccionar Fuente de la Barra de Lanzamiento"
L["CAST_FONT_TOOLTIP"] = "Selecciona el tipo de fuente utilizada para el nombre del hechizo y el texto del temporizador."
L["CAST_STATUSBAR"] = "Seleccionar Textura de la Barra de Lanzamiento"
L["CAST_STATUSBAR_TOOLTIP"] = "Selecciona el tipo de textura utilizado para la barra de lanzamiento / barra de estado."
L["CASTBAR"] = "Barra de Lanzamiento"
L["CASTBAR_COLORS"] = "Color"
L["CASTBAR_ICON"] = "Icono"
L["CASTBAR_SIZING"] = "Tamaño"
L["CASTBAR_TEXTURE_FONT"] = "Textura"
L["DEFAULT"] = "Predeterminado"
L["FONT_SIZE"] = "Tamaño de Fuente"
L["FONT_SIZE_TOOLTIP"] = "Establece el tamaño de fuente utilizado para el nombre del hechizo y el texto del temporizador."
L["FRAME_LEVEL"] = "Nivel del Marco"
L["FRAME_LEVEL_DESC"] = "Cambie el nivel del marco para superponer la barra de lanzamiento debajo o encima de otro marco."
L["GENERAL"] = "Configuración General"
L["HEIGHT"] = "Altura"
L["HEIGHT_TOOLTIP"] = "Establece la altura de la barra de lanzamiento."
L["ICON_HIDE_BORDER"] = "Ocultar borde del icono"
L["ICON_POS_X"] = "Posición de Icono X"
L["ICON_POS_Y"] = "Posición de Icono Y"
L["ICON_SHOW"] = "Mostrar icono de hechizo"
L["ICON_SIZE"] = "Tamaño del Icono"
L["ICON_SIZE_TOOLTIP"] = "Establece el tamaño del icono de hechizo de la barra de lanzamiento."
L["LSM_TEXTURE_NOTE"] = [=[
Nota: Si usa una textura / fuente de terceros personalizada y la elimina más adelante de su ordenador, deberá restablecer manualmente la textura o fuente aquí para que el complemento continúe funcionando.]=]
L["NAMEPLATE"] = "Placa identificativa"
L["PARTY"] = "Grupo"
L["PER_CHARACTER"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tConfiguraciones Específicas de Personaje"
L["PER_CHARACTER_TOOLTIP"] = "Haga clic aquí para alternar entre la configuración general y la configuración específica de este personaje."
L["PLAYER"] = "Jugador"
L["POSXY_TOOLTIP"] = "Ajuste los valores de desplazamiento XY para mover el marco."
L["REQUIRES_RESTART"] = "Deshabilitar este módulo de barra de lanzamiento requiere una recarga de su interfaz. Presione Aceptar para recargar la IU."
L["RESET_ALL"] = "Restablecer"
L["SHOW_FOR_ENEMY"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tMostrar Lanzamientos de Enemigos"
L["SHOW_FOR_FRIENDLY"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|tMostrar Lanzamientos de Aliados"
L["SHOW_SPARK"] = "Mostrar Efecto de Chispa de la Barra de Lanzamiento"
L["SHOW_TIMER"] = "Mostrar texto del temporizador"
L["SHOW_TIMER_TOOLTIP"] = "Muestra una cuenta atrás del temporizador para el lanzamiento actual."
L["STATUS_BG_COLOR"] = "Seleccionar Color de Fondo"
L["STATUS_CHANNEL_COLOR"] = "Seleccionar Color de Llenar Canal"
L["STATUS_COLOR"] = "Seleccionar Color de Llenar Lanzamiento"
L["STATUS_FAILED_COLOR"] = "Seleccionar Color de Relleno de Hechizos Fallidos"
L["STATUS_UNINTERRUPTIBLE_COLOR"] = "Seleccionar Color de Relleno Ininterrumpible"
L["TARGET"] = "Objetivo"
L["TEST"] = "Alternar Probando"
L["TEST_MODE_DRAG"] = "Modo de Prueba - Arrastre para Mover"
L["TEST_PLATE_TOOLTIP"] = [=[Muestra la barra de lanzamiento de la placa identificativa para la prueba. Puedes arrastrar la barra de lanzamiento para moverla.
Tendrá que apuntar a alguien y hacer que la placa identificativa esté visible para ver la barra de lanzamiento de prueba.
]=]
L["TEST_TARGET_TOOLTIP"] = [=[Muestra la barra de lanzamiento del marco del objetivo para la prueba. Puedes arrastrar la barra de lanzamiento para moverla.
Tendrá que apuntar a alguien primero para ver la barra de lanzamiento de prueba.
]=]
L["TEXT_COLOR"] = "Seleccionar Color de Texto"
L["TEXT_POS_X"] = "Posición de Texto X"
L["TEXT_POS_Y"] = "Posición de Texto Y"
L["TOGGLE_CASTBAR"] = "Habilitar barra de lanzamiento"
L["TOGGLE_CASTBAR_TOOLTIP"] = "Habilita o deshabilita la barra de lanzamiento para este marco de unidad específico."
L["WIDTH"] = "Anchura"
L["WIDTH_TOOLTIP"] = "Establece la anchura de la barra de lanzamiento."

