local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "koKR")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "시전 바 위치 자동 조정"
L["AUTO_POS_BAR_TOOLTIP"] = "활성화되면 유닛 프레임에 표시되는 강화 및 약화 효과의 수에 따라 시전 바의 위치를 자동 조정합니다. 외부 유닛 프레임을 사용할 경우 적용되지 않습니다."
L["BORDER_COLOR"] = "테두리 색깔 선택"
L["CAST_BORDER"] = "테두리 텍스쳐 선택"
L["CAST_BORDER_TOOLTIP"] = "시전 바 테두리의 텍스쳐를 선택합니다."
L["CAST_FONT"] = "시전 바 글꼴 설정"
L["CAST_FONT_TOOLTIP"] = "주문 이름과 타이머 텍스트의 글꼴을 선택합니다."
L["CAST_STATUSBAR"] = "시전 바 텍스쳐 선택"
L["CAST_STATUSBAR_TOOLTIP"] = "시전 바/상태 바의 텍스쳐 타입을 선택합니다."
L["CASTBAR"] = "시전 바"
L["CASTBAR_COLORS"] = "시전 바 색상"
L["CASTBAR_ICON"] = "시전 바 아이콘"
L["CASTBAR_SIZING"] = "시전 바 크기"
L["CASTBAR_TEXTURE_FONT"] = "시전 바 텍스쳐"
L["DEFAULT"] = "기본 설정"
L["FONT_SIZE"] = "글자 크기"
L["FONT_SIZE_TOOLTIP"] = "주문 이름과 타이머 텍스트의 글자 크기를 설정합니다."
L["GENERAL"] = "일반 설정"
L["HEIGHT"] = "시전 바 높이"
L["HEIGHT_TOOLTIP"] = "시전 바의 높이를 설정합니다."
L["ICON_HIDE_BORDER"] = "아이콘 테두리 숨기기"
L["ICON_POS_TOOLTIP"] = "주문 아이콘의 XY 좌표값을 조정합니다."
L["ICON_POS_X"] = "아이콘의 X 좌표값"
L["ICON_POS_Y"] = "아이콘의 Y 좌표값"
L["ICON_SIZE"] = "아이콘 크기"
L["ICON_SIZE_TOOLTIP"] = "시전 바 주문 아이콘의 크기를 설정합니다."
L["LSM_TEXTURE_NOTE"] = "참고: 외부 커스텀 텍스쳐/폰트를 사용하다가 나중에 삭제할 경우, 이 애드온에서 텍스쳐 또는 글꼴을 직접 리셋해야 애드온을 계속 사용할 수 있습니다."
L["NAMEPLATE"] = "이름표"
L["PUSHBACK"] = "시전 밀림 감지"
L["PUSHBACK_TOOLTIP"] = "시전 밀림과 언어의 저주와 같은 시전 속도 감소 효과를 감지합니다. 특정 주문과 특성의 경우 시전 밀림 효과를 방지하기 때문에 감지가 정확하지 않을 수 있습니다."
L["RESET_ALL"] = "모든 설정 초기화"
L["SHOW_CAST_INFO_ONLY"] = "시전 정보만 표시"
L["SHOW_CAST_INFO_ONLY_TOOLTIP"] = "시전 타이머를 숨기고 시전 정보만 표시합니다. 주문 페이크나 시전 밀림 효과 때문에 시전 타이머가 너무 부정확한 경우에 사용할 수 있습니다. 시전 바 높이를 0으로 만들고 테두리를 없애면 시전 바 자체도 보이지 않게 하고 주문 이름만 표시하게 할 수 있습니다."
L["SHOW_TIMER"] = "타이머 텍스트 표시"
L["SHOW_TIMER_TOOLTIP"] = "현재 시전되는 주문의 타이머를 표시합니다."
L["STATUS_CHANNEL_COLOR"] = "채널링 시 채워져 있는 부분의 색상 선택"
L["STATUS_COLOR"] = "시전 시 채워지는 부분의 색상 선택"
L["TARGET"] = "대상"
L["TEST"] = "테스트 바 표시/해제"
L["TEST_MODE_DRAG"] = "테스트 바 - 이동시키려면 드래그하세요"
L["TEST_PLATE_TOOLTIP"] = "테스트를 위해 이름표 시전 바를 표시합니다. 시전 바를 드래그함으로써 옮길 수 있습니다. 대상을 지정하고 이름표가 표시된 상태여야 테스트가 가능합니다."
L["TEST_TARGET_TOOLTIP"] = "테스트를 위해 대상 프레임 시전 바를 표시합니다. 시전 바를 드래그함으로써 옮길 수 있습니다. 대상이 선택된 상태여야 테스트할 수 있습니다."
L["TEXT_COLOR"] = "텍스트 색상 선택"
L["TOGGLE_CASTBAR"] = "시전 바 활성화"
L["TOGGLE_CASTBAR_TOOLTIP"] = "이 특정 유닛 프레임에 적용될 시전 바를 활성화/비활성화합니다."
L["WIDTH"] = "시전 바 너비"
L["WIDTH_TOOLTIP"] = "시전 바의 너비를 설정합니다."

