local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "zhTW")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "自動調整施法條位置"
L["AUTO_POS_BAR_TOOLTIP"] = "勾選此選項時，施法條將依據當前持有增益效果及其他數量自動調整位置。此選項無法與第三方頭像UI同時使用。"
L["BORDER_COLOR"] = "選擇邊框顏色"
L["BORDERSHIELD"] = "顯示無法打斷的盾牌"
L["BORDERSHIELD_TOOLTIP"] = [=[施法無法被打斷時，在施法條周圍顯示盾牌。停用這個選項時，無法打斷的施法會顯示灰色背景。

|cffffff00按住組合按鍵，像是 SHIFT 或 CTRL 鍵不放，再點一下 "開關測試模式" 按鈕可以測試顯示盾牌的施法條。|r]=]
L["CAST_BORDER"] = "施法條外框紋理"
L["CAST_BORDER_TOOLTIP"] = "選擇施法條外框紋理"
L["CAST_FONT"] = "施法條字體"
L["CAST_FONT_TOOLTIP"] = "選擇法術名稱與詠唱時間的字體"
L["CAST_STATUSBAR"] = "施法條背景紋理"
L["CAST_STATUSBAR_TOOLTIP"] = "選擇施法條/狀態條的背景紋理"
L["CASTBAR"] = "施法條"
L["CASTBAR_COLORS"] = "施法條顏色"
L["CASTBAR_ICON"] = "施法條圖示"
L["CASTBAR_SIZING"] = "施法條尺寸"
L["CASTBAR_TEXTURE_FONT"] = "施法條背景紋理"
L["DEFAULT"] = "預設值"
L["FONT_SIZE"] = "字體大小"
L["FONT_SIZE_TOOLTIP"] = "選擇法術名稱與詠唱時間的字體大小"
L["FRAME_LEVEL"] = "框架層級"
L["FRAME_LEVEL_DESC"] = "更改框架層級，讓施法條在其他框架前方或後方。"
L["GENERAL"] = "主設定"
L["HEIGHT"] = "施法條高度"
L["HEIGHT_TOOLTIP"] = "設定施法條高度"
L["ICON_HIDE_BORDER"] = "隱藏圖示邊框"
L["ICON_POS_X"] = "圖示水平位置"
L["ICON_POS_Y"] = "圖示垂直位置"
L["ICON_SHOW"] = "顯示法術圖示"
L["ICON_SIZE"] = "圖示尺寸"
L["ICON_SIZE_TOOLTIP"] = "設定施法條圖示尺寸"
L["LSM_TEXTURE_NOTE"] = "注意：若您刪除了進行此設定時使用的第三方背景紋理/字體包，您需要於此頁面重新設定。"
L["NAMEPLATE"] = "血條"
L["PARTY"] = "隊友"
L["PER_CHARACTER"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|t角色專用設定"
L["PER_CHARACTER_TOOLTIP"] = "點一下在通用設定和這個角色的專用設定之間切換。"
L["PLAYER"] = "玩家"
L["POSXY_TOOLTIP"] = "調整水平和垂直位置的數值來移動框架。"
L["REQUIRES_RESTART"] = "停用這個施法條模組需要重新載入介面，請按下接受來重新載入。"
L["RESET_ALL"] = "重置所有設定"
L["SHOW_FOR_ENEMY"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|t顯示敵方施法"
L["SHOW_FOR_FRIENDLY"] = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|t顯示友方施法"
L["SHOW_SPARK"] = "顯示施法條亮點效果"
L["SHOW_TIMER"] = "顯示詠唱時間"
L["SHOW_TIMER_TOOLTIP"] = "顯示目前施展法術的詠唱時間倒數"
L["STATUS_BG_COLOR"] = "選擇背景顏色"
L["STATUS_CHANNEL_COLOR"] = "選擇引導施法顏色"
L["STATUS_COLOR"] = "選擇施法顏色"
L["STATUS_FAILED_COLOR"] = "選擇施法失敗顏色"
L["STATUS_UNINTERRUPTIBLE_COLOR"] = "選擇無法打斷顏色"
L["TARGET"] = "目標頭像"
L["TEST"] = "開關測試模式"
L["TEST_MODE_DRAG"] = "測試模式：拉曳以移動施法條"
L["TEST_PLATE_TOOLTIP"] = "顯示測試用的角色頭頂施法條。在此模式下您可以拉曳施法條以調整位置。測試時請先開啟顯示角色頭頂施法條並點選一個目標。"
L["TEST_TARGET_TOOLTIP"] = "顯示測試用的人物頭像施法條。在此模式下您可以拉曳施法條以調整位置。測試時請先點選一個目標以顯示人物頭像。"
L["TEXT_COLOR"] = "選擇文字顏色"
L["TEXT_POS_X"] = "文字水平位置"
L["TEXT_POS_Y"] = "文字垂直位置"
L["TOGGLE_CASTBAR"] = "啟用施法條功能"
L["TOGGLE_CASTBAR_TOOLTIP"] = "設定是否在此UI設定啟用施法條功能"
L["WIDTH"] = "施法條寬度"
L["WIDTH_TOOLTIP"] = "設定施法條寬度"

