-- make default var config-able, based on client locale
local locale = GetLocale()
local l
if (locale == "zhTW" or locale == "zhCN" or locale == "koKR") then 
	l = 2
else
	l = 0
end

-- default "constants" like #define in C :)
MONKEYQUEST_DELAY							= 0.3;
MONKEYQUEST_PADDING							= 25;
MONKEYQUEST_MAX_BUTTONS						= 60;

-- default settings
MONKEYQUEST_DEFAULT_CRASHCOLOUR				= { r = 1.0, g = 0.6901960784313725, b = 0.0 };
MONKEYQUEST_DEFAULT_ALPHA					= 0.5;
MONKEYQUEST_DEFAULT_HIGHLIGHT_ALPHA			= 1.0;
MONKEYQUEST_DEFAULT_FRAME_ALPHA				= 1.0;
MONKEYQUEST_DEFAULT_WIDTH					= 255;
MONKEYQUEST_DEFAULT_LEFT					= 500;
MONKEYQUEST_DEFAULT_TOP						= 500;
MONKEYQUEST_DEFAULT_BOTTOM					= 539;
MONKEYQUEST_DEFAULT_SHOWNOOBTIPS			= true;
MONKEYQUEST_DEFAULT_QUESTPADDING			= 0;
MONKEYQUEST_DEFAULT_SHOWZONEHIGHLIGHT		= true;
MONKEYQUEST_DEFAULT_SHOWQUESTLEVEL			= true;
MONKEYQUEST_DEFAULT_DISPLAY					= true;
MONKEYQUEST_DEFAULT_DEFAULTANCHOR			= false;
MONKEYQUEST_DEFAULT_ANCHOR					= "ANCHOR_TOPLEFT";
MONKEYQUEST_DEFAULT_OBJECTIVES				= true;
MONKEYQUEST_DEFAULT_MINIMIZED				= false;
MONKEYQUEST_DEFAULT_SHOWHIDDEN				= false;
MONKEYQUEST_DEFAULT_NOHEADERS				= false;
MONKEYQUEST_DEFAULT_ALWAYSHEADERS			= false;
MONKEYQUEST_DEFAULT_NOBORDER				= false;
MONKEYQUEST_DEFAULT_GROWUP					= false;
MONKEYQUEST_DEFAULT_SHOWNUMQUESTS			= true;
MONKEYQUEST_DEFAULT_SHOWDAILYNUMQUESTS		= false;
MONKEYQUEST_DEFAULT_LOCKED					= false;
MONKEYQUEST_DEFAULT_HIDECOMPLETEDQUESTS		= false;
MONKEYQUEST_DEFAULT_HIDECOMPLETEDOBJECTIVES	= false;
MONKEYQUEST_DEFAULT_ALLOWRIGHTCLICK			= true;
MONKEYQUEST_DEFAULT_SHOWTOOLTIPOBJECTIVES	= true;
MONKEYQUEST_DEFAULT_HIDETITLEBUTTONS		= false;
MONKEYQUEST_DEFAULT_HIDETITLE				= false;
MONKEYQUEST_DEFAULT_WORKCOMPLETE			= true;
MONKEYQUEST_DEFAULT_COLOURTITLE				= false;
MONKEYQUEST_DEFAULT_FONTHEIGHT				= 12;
MONKEYQUEST_DEFAULT_FONT					= l;
MONKEYQUEST_DEFAULT_CRASHBORDER				= false;
MONKEYQUEST_DEFAULT_QUESTTITLECOLOUR		= "|cFFFFFFFF";
MONKEYQUEST_DEFAULT_HEADEROPENCOLOUR		= "|cFFBFBFFF";
MONKEYQUEST_DEFAULT_HEADERCLOSEDCOLOUR		= "|cFF9F9FFF";
MONKEYQUEST_DEFAULT_OVERVIEWCOLOUR			= "|cFF7F7F7F";
MONKEYQUEST_DEFAULT_SPECIALOBJECTIVECOLOUR	= "|cFFFFFF00";
MONKEYQUEST_DEFAULT_INITIALOBJECTIVECOLOUR	= "|cFFD82619";
MONKEYQUEST_DEFAULT_MIDOBJECTIVECOLOUR		= "|cFFFFFF00";
MONKEYQUEST_DEFAULT_COMPLETEOBJECTIVECOLOUR	= "|cFF00FF19";
MONKEYQUEST_DEFAULT_FINISHOBJECTIVECOLOUR	= "|cFF33DDFF";
MONKEYQUEST_DEFAULT_ZONEHILIGHTCOLOUR		= "|cff494961";
MONKEYQUEST_DEFAULT_COLOURSUBOBJECTIVES		= true;
MONKEYQUEST_DEFAULT_ITEMSENABLED			= false;
MONKEYQUEST_DEFAULT_ITEMSONLEFT				= true;
MONKEYQUEST_DEFAULT_HIDEHEADER				= false;
MONKEYQUEST_DEFAULT_HIDEQUESTSENABLED		= true;
MONKEYQUEST_DEFAULT_COLOURDONEORFAILED		= false;
MONKEYQUEST_DEFAULT_QUESTTEXTTOOLTIP		= false;

-- Blizzard style quest tracker settings
MONKEYQUEST_BLIZZARD_FRAME_ALPHA			= 1.0;
MONKEYQUEST_BLIZZARD_ALPHA					= 0.0;
MONKEYQUEST_BLIZZARD_QUESTPADDING			= 5;
MONKEYQUEST_BLIZZARD_SHOWQUESTLEVEL			= false;
MONKEYQUEST_BLIZZARD_OBJECTIVES				= false;
MONKEYQUEST_BLIZZARD_NOBORDER				= true;
MONKEYQUEST_BLIZZARD_SHOWNUMQUESTS			= true;
MONKEYQUEST_BLIZZARD_WORKCOMPLETE			= false;
MONKEYQUEST_BLIZZARD_QUESTTITLECOLOUR		= "|cffffe2 0";
MONKEYQUEST_BLIZZARD_COMPLETEOBJECTIVECOLOUR	= "|cff 0ff19";
MONKEYQUEST_BLIZZARD_FINISHOBJECTIVECOLOUR	= "|cffeefffa";
MONKEYQUEST_BLIZZARD_FONT = 2;
MONKEYQUEST_BLIZZARD_COLOURSUBOBJECTIVES	= false;
MONKEYQUEST_BLIZZARD_ITEMSONLEFT			= false;
MONKEYQUEST_BLIZZARD_HIDEHEADER				= true;
