
local L = LibStub('AceLocale-3.0'):NewLocale(..., 'koKR')
if not L then return end

L["Add advance rule"] = "고급 규칙 추가"
L["Add extension filter to LibItemSearch-1.2"] = "LibItemSearch-1.2에 확장 필터 추가"
--[[Translation missing --]]
--[[ L["Add rule"] = ""--]] 
L["Advancee rules use LibItemSearch-1.2"] = "고급 규칙에 LibItemSearch-1.2를 사용합니다."
L["Already exists"] = "이미 존재함"
L["Are you sure |cffff191919DELETE|r rule and its |cffff1919SUBRULES|r?"] = "규칙과 |cffff1919하위 규칙|r을 |cffff1919삭제|r 하시겠습니까?"
L["Are you sure |cffff191919DELETE|r rule?"] = "규칙을 |cffff1919삭제|r 하시겠습니까?"
L["Are you sure to |cffff1919RESET|r saving rules?"] = "보관 규칙을 |cffff1919재설정|r 하시겠습니까?"
L["Are you sure to |cffff1919RESET|r sorting rules?"] = "정리 규칙을 |cffff1919재설정|r 하시겠습니까?"
L["Are you sure you want to restore the current Settings?"] = "현재 설정을 복원 하시겠습니까?"
L["Bag button features"] = "가방 버튼 기능"
L["Bank and bag stacking together"] = "은행과 가방을 함께 중첩"
L["Bank button features"] = "은행 버튼 기능"
L["Character Specific Settings"] = "캐릭터 개별 설정"
L["COMMENT_CLASS"] = "직업 아이템"
L["COMMENT_MOUNT"] = "탈것"
L["Drag to modify the sorting order"] = "정리 순서를 수정하려면 드래그 합니다."
--[[Translation missing --]]
--[[ L["Edit rule"] = ""--]] 
L["Enable chat message"] = "대화 메세지 사용"
L["Enjoy!"] = "즐기세요!"
L["Global"] = "전역"
L["Help"] = "도움말"
L["ITEM_TAG: Cloth"] = "천"
L["ITEM_TAG: Cooking"] = "요리"
L["ITEM_TAG: Elemental"] = "원소"
L["ITEM_TAG: Enchanting"] = "마법부여"
L["ITEM_TAG: Herb"] = "약초"
L["ITEM_TAG: Jewelry"] = "보석"
L["ITEM_TAG: Leather"] = "가죽"
L["ITEM_TAG: Metal & Stone"] = "광석과 주괴"
L["ITEM_TAG: Mount"] = "탈것"
L["ITEM_TAG: Pet"] = "애완동물"
L["Keep bank items stack full"] = "은행 아이템을 중첩하여 채움"
L["KEYWORD_CLASS"] = "직업"
L["KEYWORD_MOUNT"] = "타거나 내립니다"
L["Leave bank, pack cancel."] = "은행을 떠나 정리를 취소합니다."
L["Left Click"] = "좌클릭"
L["Name (Optional)"] = "이름 (선택 사항)"
L["None"] = "없음"
L["OPEN_OPTIONS"] = "설정 열기"
L["OPEN_RULE_OPTIONS"] = "규칙 설정 열기"
L["Pack finish."] = "정리 마침."
L["Packing now"] = "정리하는 중"
L["Player enter combat, pack cancel."] = "플레이어 전투 참여로 정리를 취소합니다."
L["Player in combat"] = "플레이어가 전투 중입니다"
L["Player is dead"] = "플레이어가 죽었습니다"
L["Please drop the item, money or skills."] = "아이템, 돈 또는 기술을 떨어뜨려 주세요."
L["Put in an item to add simple rule"] = "간단한 규칙을 추가하기 위해 아이템을 넣습니다."
L["Put where?"] = "어디에 넣을까요?"
L["Reset saving rules"] = "보관 규칙 재설정"
L["Reset sorting rules"] = "정리 규칙 재설정"
L["Restore default Settings"] = "기본 설정 복원"
L["Reverse pack"] = "반대로 정리"
L["Right Click"] = "우클릭"
L["Root"] = "최상위"
L["Rule"] = "규칙"
--[[Translation missing --]]
--[[ L["Rules restore to default."] = ""--]] 
L["SAVE"] = "은행에 보관"
L["Save to bank when default packing"] = "기본 정리 시 은행에 보관"
L["Saving rules"] = "보관 규칙"
L["Select an icon (Optional)"] = "아이콘 선택 (선택 사항)"
L["Some slot is locked"] = "일부 칸이 잠겨 있음."
L["SORT"] = "기본 정리"
L["SORT_ASC"] = "오름차순 정리"
L["SORT_BAG"] = "가방 정리"
L["SORT_BAG_ASC"] = "가방 오름차순 정리"
L["SORT_BAG_DESC"] = "가방 내림차순 정리"
L["SORT_BANK"] = "은행 정리"
L["SORT_BANK_ASC"] = "은행 오름차순 정리"
L["SORT_BANK_DESC"] = "은행 내림차순 정리"
L["SORT_DESC"] = "내림차순 정리"
L["Sorting rules"] = "정리 규칙"
L["Tools"] = "도구"
--[[Translation missing --]]
--[[ L["UPDATE_RULES_CONFIRM"] = ""--]] 

