
local L = LibStub('AceLocale-3.0'):NewLocale(..., 'zhTW')
if not L then return end

--[[Translation missing --]]
--[[ L["Add advance rule"] = ""--]] 
--[[Translation missing --]]
--[[ L["Add extension filter to LibItemSearch-1.2"] = ""--]] 
--[[Translation missing --]]
--[[ L["Advancee rules use LibItemSearch-1.2"] = ""--]] 
--[[Translation missing --]]
--[[ L["Already exists"] = ""--]] 
--[[Translation missing --]]
--[[ L["Are you sure |cffff191919DELETE|r rule and its |cffff1919SUBRULES|r?"] = ""--]] 
--[[Translation missing --]]
--[[ L["Are you sure |cffff191919DELETE|r rule?"] = ""--]] 
--[[Translation missing --]]
--[[ L["Are you sure to |cffff1919RESET|r saving rules?"] = ""--]] 
--[[Translation missing --]]
--[[ L["Are you sure to |cffff1919RESET|r sorting rules?"] = ""--]] 
--[[Translation missing --]]
--[[ L["Bag button features"] = ""--]] 
--[[Translation missing --]]
--[[ L["Bank button features"] = ""--]] 
--[[Translation missing --]]
--[[ L["Character Specific Settings"] = ""--]] 
--[[Translation missing --]]
--[[ L["COMMENT_CLASS"] = ""--]] 
--[[Translation missing --]]
--[[ L["COMMENT_MOUNT"] = ""--]] 
--[[Translation missing --]]
--[[ L["Drag to modify the sorting order"] = ""--]] 
--[[Translation missing --]]
--[[ L["Enable chat message"] = ""--]] 
--[[Translation missing --]]
--[[ L["Enjoy!"] = ""--]] 
--[[Translation missing --]]
--[[ L["Global"] = ""--]] 
--[[Translation missing --]]
--[[ L["Help"] = ""--]] 
--[[Translation missing --]]
--[[ L["KEYWORD_CLASS"] = ""--]] 
--[[Translation missing --]]
--[[ L["KEYWORD_MOUNT"] = ""--]] 
L["Leave bank, pack cancel."] = "離開銀行，整理中止。"
--[[Translation missing --]]
--[[ L["Left Click"] = ""--]] 
--[[Translation missing --]]
--[[ L["Name (Optional)"] = ""--]] 
--[[Translation missing --]]
--[[ L["None"] = ""--]] 
--[[Translation missing --]]
--[[ L["OPEN_OPTIONS"] = ""--]] 
--[[Translation missing --]]
--[[ L["OPEN_RULE_OPTIONS"] = ""--]] 
L["Pack finish."] = "整理完成"
L["Packing now"] = "正在整理"
L["Player enter combat, pack cancel."] = "進入戰鬥，整理中止。"
L["Player in combat"] = "正在戰鬥"
L["Player is dead"] = "角色已死亡"
L["Please drop the item, money or skills."] = true
--[[Translation missing --]]
--[[ L["Put in an item to add simple rule"] = ""--]] 
--[[Translation missing --]]
--[[ L["Put where?"] = ""--]] 
--[[Translation missing --]]
--[[ L["Reset saving rules"] = ""--]] 
--[[Translation missing --]]
--[[ L["Reset sorting rules"] = ""--]] 
--[[Translation missing --]]
--[[ L["Reverse pack"] = ""--]] 
--[[Translation missing --]]
--[[ L["Right Click"] = ""--]] 
--[[Translation missing --]]
--[[ L["Root"] = ""--]] 
--[[Translation missing --]]
--[[ L["Rule"] = ""--]] 
--[[Translation missing --]]
--[[ L["SAVE"] = ""--]] 
--[[Translation missing --]]
--[[ L["Save to bank when default packing"] = ""--]] 
--[[Translation missing --]]
--[[ L["Saving rules"] = ""--]] 
--[[Translation missing --]]
--[[ L["Select an icon (Optional)"] = ""--]] 
--[[Translation missing --]]
--[[ L["Some slot is locked"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_ASC"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_BAG"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_BAG_ASC"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_BAG_DESC"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_BANK"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_BANK_ASC"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_BANK_DESC"] = ""--]] 
--[[Translation missing --]]
--[[ L["SORT_DESC"] = ""--]] 
--[[Translation missing --]]
--[[ L["Sorting rules"] = ""--]] 
--[[Translation missing --]]
--[[ L["Tools"] = ""--]] 

