
local L = LibStub('AceLocale-3.0'):NewLocale(..., 'zhTW')
if not L then return end

L["Add advance rule"] = "添加高級規則"
L["Add extension filter to LibItemSearch-1.2"] = "將擴展的過濾器添加到LibItemSearch-1.2"
--[[Translation missing --]]
--[[ L["Add rule"] = ""--]] 
L["Advancee rules use LibItemSearch-1.2"] = "高級規則使用LibItemSearch-1.2"
L["Already exists"] = "已經存在"
L["Are you sure |cffff191919DELETE|r rule and its |cffff1919SUBRULES|r?"] = "確定|cffff1919刪除|r規則和它的|cffff1919子規則|r嗎？"
L["Are you sure |cffff191919DELETE|r rule?"] = "你確定|cffff1919刪除|r規則嗎？"
L["Are you sure to |cffff1919RESET|r saving rules?"] = "你確定|cffff1919重置|r保存規則？"
L["Are you sure to |cffff1919RESET|r sorting rules?"] = "你確定|cffff1919重置|r排序規則？"
L["Are you sure you want to restore the current Settings?"] = "你確定要重置當前設置嗎？"
L["Bag button features"] = "背包按鈕功能"
L["Bank and bag stacking together"] = "銀行和背包一起堆疊"
L["Bank button features"] = "銀行按鈕功能"
L["Character Specific Settings"] = "角色獨立設置"
L["COMMENT_CLASS"] = "職業物品"
L["COMMENT_MOUNT"] = "坐騎"
L["Drag to modify the sorting order"] = "拖動以改變規則順序"
--[[Translation missing --]]
--[[ L["Edit rule"] = ""--]] 
L["Enable chat message"] = "啟用聊天窗口消息"
L["Enjoy!"] = true
L["Global"] = "全局"
L["Help"] = "幫助"
L["ITEM_TAG: Cloth"] = "布"
L["ITEM_TAG: Cooking"] = "烹飪"
L["ITEM_TAG: Elemental"] = "元素"
L["ITEM_TAG: Enchanting"] = "附魔"
L["ITEM_TAG: Herb"] = "草藥"
L["ITEM_TAG: Jewelry"] = "寶石"
L["ITEM_TAG: Leather"] = "皮"
L["ITEM_TAG: Metal & Stone"] = "金屬和礦石"
L["ITEM_TAG: Mount"] = "坐騎"
L["ITEM_TAG: Pet"] = "寵物"
L["Keep bank items stack full"] = "保持銀行物品堆滿"
L["KEYWORD_CLASS"] = "職業"
L["KEYWORD_MOUNT"] = "招喚與解散"
L["Leave bank, pack cancel."] = "離開銀行，整理中止。"
L["Left Click"] = "左鍵"
L["Name (Optional)"] = "名稱（可選）"
L["None"] = "無"
L["OPEN_OPTIONS"] = "打開設置"
L["OPEN_RULE_OPTIONS"] = "打開規則設置"
L["Pack finish."] = "整理完成"
L["Packing now"] = "正在整理"
L["Player enter combat, pack cancel."] = "進入戰鬥，整理中止。"
L["Player in combat"] = "正在戰鬥"
L["Player is dead"] = "角色已死亡"
L["Please drop the item, money or skills."] = true
L["Put in an item to add simple rule"] = "放下一個物品以添加簡單規則"
L["Put where?"] = "放在哪？"
L["Reset saving rules"] = "重置保存規則"
L["Reset sorting rules"] = "重置排序規則"
L["Restore default Settings"] = "恢覆默認設置"
L["Reverse pack"] = "反向整理"
L["Right Click"] = "右鍵"
L["Root"] = "根"
L["Rule"] = "規則"
--[[Translation missing --]]
--[[ L["Rules restore to default."] = ""--]] 
L["SAVE"] = "保存"
L["Save to bank when default packing"] = "默認整理同時保存到銀行"
L["Saving rules"] = "保存規則"
L["Select an icon (Optional)"] = "選擇一個圖標（可選）"
L["Some slot is locked"] = "一些物品已鎖定"
L["SORT"] = "默認整理"
L["SORT_ASC"] = "順序整理全部"
L["SORT_BAG"] = "整理背包"
L["SORT_BAG_ASC"] = "順序整理背包"
L["SORT_BAG_DESC"] = "逆序整理背包"
L["SORT_BANK"] = "整理銀行"
L["SORT_BANK_ASC"] = "順序整理銀行"
L["SORT_BANK_DESC"] = "逆序整理銀行"
L["SORT_DESC"] = "逆序整理背包"
L["Sorting rules"] = "排序規則"
L["Tools"] = "工具"
--[[Translation missing --]]
--[[ L["UPDATE_RULES_CONFIRM"] = ""--]] 

