-- Not translations
MkQL_MAX_REWARDS						= 10
MONKEYQUESTLOG_TITLE					= "MonkeyQuestLog"
MONKEYQUESTLOG_VERSION					= "0.9.37"
MONKEYQUESTLOG_TITLE_VERSION			= MONKEYQUESTLOG_TITLE .. " v" .. MONKEYQUESTLOG_VERSION
MONKEYQUESTLOG_INFO_COLOUR				= "|cffffff00"

-- English, the default
MONKEYQUESTLOG_DESCRIPTION				= "Displays the full quest description for MonkeyQuest"
MONKEYQUESTLOG_LOADED_MSG				= MONKEYQUESTLOG_INFO_COLOUR .. MONKEYQUESTLOG_TITLE .. " v" .. MONKEYQUESTLOG_VERSION .. " loaded"

MONKEYQUESTLOG_DESC_HEADER				= "Description"
MONKEYQUESTLOG_REWARDS_HEADER			= "Rewards"
MkQL_REWARDSCHOOSE_TXT					= "Choose one of:"
MkQL_REWARDSRECEIVE_TXT					= "Receive all of:"
MkQL_SHARE_TXT							= "Share"
MkQL_ABANDON_TXT						= "Abandon"


if (GetLocale() == "zhTW") then
MONKEYQUESTLOG_TITLE					= "MQ 任務日誌"
MONKEYQUESTLOG_DESCRIPTION				= "顯示完整任務說明"
MONKEYQUESTLOG_LOADED_MSG				= MONKEYQUESTLOG_INFO_COLOUR .. MONKEYQUESTLOG_TITLE .. " v" .. MONKEYQUESTLOG_VERSION .. " 已載入"

MONKEYQUESTLOG_DESC_HEADER				= "描述"
MONKEYQUESTLOG_REWARDS_HEADER			= "獎勵"
MkQL_REWARDSCHOOSE_TXT					= "你可以從這些獎勵物品中選擇一件:"
MkQL_REWARDSRECEIVE_TXT					= "你將得到:"
MkQL_SHARE_TXT							= "分享任務"
MkQL_ABANDON_TXT						= "放棄任務"

end

if (GetLocale() == "zhCN") then
    MONKEYQUESTLOG_TITLE					= "MQ 任务日志"
    MONKEYQUESTLOG_DESCRIPTION				= "显示完整任务说明"
    MONKEYQUESTLOG_LOADED_MSG				= MONKEYQUESTLOG_INFO_COLOUR .. MONKEYQUESTLOG_TITLE .. " v" .. MONKEYQUESTLOG_VERSION .. " 已加载"
    
    MONKEYQUESTLOG_DESC_HEADER				= "描述"
    MONKEYQUESTLOG_REWARDS_HEADER			= "奖励"
    MkQL_REWARDSCHOOSE_TXT					= "你可以从这些奖励物品中选择一件:"
    MkQL_REWARDSRECEIVE_TXT					= "你将得到:"
    MkQL_SHARE_TXT							= "分享任务"
    MkQL_ABANDON_TXT						= "放弃任务"
    
end
