
DCT_TEXT_PAGE = ""
DCT_SA_FAILED = ""
DCT_SA_SUCCESS = ""
DCT_SA_YOU = ""
DCT_SA_SELF = ""
DCT_SA_OPTION = ""
DCT_SA_OPTION_ADD_SUCCESS = ""
DCT_SA_OPTION_ADD_FAILED = ""

DCTSA_TXT_FilterDDCList = {
	{"","DCTSA_FILTER_CASTSTART"},
	{"","DCTSA_FILTER_BUFF"},
	{"","DCTSA_FILTER_DISPELLED"},
	{"","DCTSA_FILTER_CASTSUCCESS"},
}

DCT_SaCfg_Event = {

	EventFrames = {
		["DCTSA_SHOW_CASTSTART_YOURTARGET"] = {x = 200,y = -140, title = "", tooltipText = ""},
		["DCTSA_SHOW_BUFFGET_YOURTARGET"] = {x = 200,y = -170, title = "", tooltipText = ""},
		["DCTSA_SHOW_BUFFFADE_YOURTARGET"] = {x = 200,y = -200, title = "", tooltipText = ""},
		["DCTSA_SHOW_DISPELLED_YOURTARGET"] = {x = 200,y = -230, title = "", tooltipText = ""},
		["DCTSA_SHOW_CASTSUCCESS_YOURTARGET"] = {x = 200,y = -260, title = "", tooltipText = ""},

		["DCTSA_SHOW_CASTSTART_FOCUS"] = {x = 405,y = -140, title = "", tooltipText = ""},
		["DCTSA_SHOW_BUFFGET_FOCUS"] = {x = 405,y = -170, title = "", tooltipText = ""},
		["DCTSA_SHOW_BUFFFADE_FOCUS"] = {x = 405,y = -200, title = "", tooltipText = ""},
		["DCTSA_SHOW_DISPELLED_FOCUS"] = {x = 405,y = -230, title = "", tooltipText = ""},
		["DCTSA_SHOW_CASTSUCCESS_FOCUS"] = {x = 405,y = -260, title = "", tooltipText = ""},

		["DCTSA_SHOW_CASTSTART"] = {x = 550,y = -140, title = "", tooltipText = ""},
		["DCTSA_SHOW_BUFFGET"] = {x = 550,y = -170, title = "", tooltipText = ""},
		["DCTSA_SHOW_BUFFFADE"] = {x = 550,y = -200, title = "", tooltipText = ""},
		["DCTSA_SHOW_DISPELLED"] = {x = 550,y = -230, title = "", tooltipText = ""},
		["DCTSA_SHOW_CASTSUCCESS"] = {x = 550,y = -260, title = "", tooltipText = ""},

	},

	CheckButtons = {
		["DCTSA_ENABLE"] = {x = 195,y = -25, title = "", tooltipText = ""},
		["DCTSA_ENABLE_ONPVP"] = {x = 195,y = -55, title = "", tooltipText = ""},
		["DCTSA_ENABLE_ONCOMBAT"] = {x = 435,y = -55, title = "", tooltipText = ""},
		["DCTSA_CASTSUCCESS_ONLYTOYOU"] = {x = 195,y = -80, title =  "", tooltipText = ""},
		["DCTSA_MERGE_CASTSUCCESS_AND_BUFFGET"] = {x = 435,y = -80, title =  "", tooltipText = ""},
		["DCTSA_SSC_Spell"] = {x = 195,y = -105, title =  "", tooltipText = ""},
		["DCTSA_CASTTIME"] = {x = 435,y = -105, title =  "", tooltipText = ""},

		["DCTSA_FILTER_ENABLE"] = {x = 195,y = -290, title = "", tooltipText = ""},
		["DCTSA_FILTER_MODE"] = {x = 380,y = -320, title = "", tooltipText = ""},
	},
};


