local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "zhCN", false, true)

if not L then return end
-- Simplified Chinese translation by swimstiger https://www.curseforge.com/members/swimstiger
if L then
L["Boat to Auberdine"] = "去奥伯丁的船"
L["Boat to Booty Bay"] = "去藏宝海湾的船"
L["Boat to Darnassus"] = "去达纳苏斯的船"
L["Boat to Menethil Harbor"] = "去米奈希尔港的船"
L["Boat to Ratchet"] = "去棘齿城的船"
L["Boat to Theramore Isle"] = "去塞拉摩的船"
L["config_boat"] = "船"
L["config_boat_alliance"] = "联盟船"
L["config_boat_alliance_desc"] = "显示联盟方船的位置"
L["config_boat_desc"] = "显示船的位置"
L["config_icon_alpha"] = "图标透明度"
L["config_icon_alpha_desc"] = "控制图标的透明程度"
L["config_icon_scale"] = "图标缩放"
L["config_icon_scale_desc"] = "对图标进行缩放"
L["config_note"] = "备注"
L["config_note_desc"] = "在鼠标提示中显示备注信息"
L["config_plugin_desc"] = "在世界地图和小地图上显示船和飞艇的位置"
L["config_restore_nodes"] = "重置隐藏的标记"
L["config_restore_nodes_desc"] = "重新显示所有你右击并选择“隐藏”的标记"
L["config_tram"] = "矿道地铁"
L["config_tram_desc"] = "显示暴风城到铁炉堡的矿道地铁入口位置"
L["config_what_to_display"] = "要显示哪些图标？"
L["config_what_to_display_desc"] = "控制地图上显示的图标种类"
L["config_zeppelin"] = "飞艇"
L["config_zeppelin_desc"] = "显示飞艇的位置"
L["config_zeppelin_horde"] = "部落飞艇"
L["config_zeppelin_horde_desc"] = "显示部落方飞艇的位置"
L["Deeprun Tram to Ironforge"] = "去铁炉堡的矿道地铁"
L["Deeprun Tram to Stormwind"] = "去暴风城的矿道地铁"
L["Zeppelin to Orgrimmar"] = "去奥格瑞玛的飞艇"
L["Zeppelin to Stranglethorn Vale"] = "去荆棘谷的飞艇"
L["Zeppelin to Undercity"] = "去幽暗城的飞艇"
end