local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide (BCC)", "frFR", false, true)

if not L then return end
-- French translation by scaxfull https://www.curseforge.com/members/scaxfull
if L then
L["Boat to Auberdine"] = "Bateau vers Auberdine"
L["Boat to Booty Bay"] = "Bateau vers Baie-du-Butin"
L["Boat to Darnassus"] = "Bateau vers Darnassus"
L["Boat to Menethil Harbor"] = "Bateau vers Port de Menethil"
L["Boat to Ratchet"] = "Bateau vers Ratchet"
L["Boat to Theramore"] = "Bateau vers Theramore"
L["config_boat"] = "Bateau"
L["config_boat_alliance"] = "Bateau de l'Alliance"
L["config_boat_alliance_desc"] = "Afficher locations des bateaux de l'Alliance"
L["config_boat_desc"] = "Afficher locations des bateaux"
L["config_icon_alpha"] = "Transparence des icônes"
L["config_icon_alpha_desc"] = "La transparence des icônes"
L["config_icon_scale"] = "Taille des icônes"
L["config_icon_scale_desc"] = "L'échelle des icônes"
L["config_note"] = "Note"
L["config_note_desc"] = "Affiche les notes supplémentaires du nœud, lorsqu'il est disponible."
L["config_plugin_desc"] = "Affiche les emplacements des bateaux et des zepplin sur la carte du monde et la mini-carte"
L["config_restore_nodes"] = "Réinitialiser les nœuds cachés"
L["config_restore_nodes_desc"] = "Affichez tous les nœuds que vous avez masqués manuellement en cliquant dessus avec le bouton droit de la souris et en choisissant \"masquer\""
L["config_tram"] = "Tram des Profondeurs"
L["config_tram_desc"] = "Montrez les emplacements des trams de profondeurs à Stormwind et Ironforge"
L["config_what_to_display"] = "Quoi afficher?"
L["config_what_to_display_desc"] = "Ces paramètres contrôlent le type d’icônes à afficher."
L["config_zeppelin"] = "Zeppelin"
L["config_zeppelin_desc"] = "Afficher locations des Zepplins"
L["config_zeppelin_horde"] = "Zepplin de Horde"
L["config_zeppelin_horde_desc"] = "Montrez les emplacements des Zeppelin de la Horde."
L["Deeprun Tram to Ironforge"] = "Tram des Profondeurs vers Ironforge"
L["Deeprun Tram to Stormwind"] = "Tram des Profondeurs vers Stormwind"
L["Zeppelin to Orgrimmar"] = "Zeppelin vers Orgrimmar"
L["Zeppelin to Stranglethorn Vale"] = "Zeppelin vers Vallée de Strangleronce"
L["Zeppelin to Undercity"] = " Zeppelin vers Undercity"
end