local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide (BCC)", "koKR", false, true)

if not L then return end
-- Korean translation by blacknib https://www.curseforge.com/members/blacknib
if L then
L["Boat to Auberdine"] = "아우버다인 방향 배"
L["Boat to Booty Bay"] = "무법항 방향 배"
L["Boat to Darnassus"] = "다르나서스 방향 배"
L["Boat to Menethil Harbor"] = "메네실 항구 방향 배"
L["Boat to Ratchet"] = "톱니항 방향 배"
L["Boat to Theramore"] = "테라모어 방향 배"
L["config_boat"] = "배"
L["config_boat_alliance"] = "얼라이언스 배"
L["config_boat_alliance_desc"] = "얼라이언스의 배 위치를 표시합니다."
L["config_boat_desc"] = "배의 위치를 표시합니다."
L["config_icon_alpha"] = "아이콘 투명도"
L["config_icon_alpha_desc"] = "아이콘의 투명도입니다."
L["config_icon_scale"] = "아이콘 크기"
L["config_icon_scale_desc"] = "아이콘의 크기입니다."
L["config_note"] = "노트"
L["config_note_desc"] = "가능한 경우 노드에 추가 노트를 표시합니다."
L["config_plugin_desc"] = "세계 지도와 미니맵에 배와 비행선의 위치를 표시합니다."
L["config_restore_nodes"] = "숨겨진 노드 재설정"
L["config_restore_nodes_desc"] = "우-클릭하고 \\\"숨김\\\"을 선택하여 수동으로 숨긴 모든 노드를 표시합니다."
L["config_tram"] = "깊은굴 지하철"
L["config_tram_desc"] = "스톰위드와 아이언포지의 깊은굴 지하철 위치를 표시합니다."
L["config_what_to_display"] = "무엇을 표시할까요?"
L["config_what_to_display_desc"] = "이 설정은 표시할 아이콘의 종류를 제어합니다."
L["config_zeppelin"] = "비행선"
L["config_zeppelin_desc"] = "비행선의 위치를 표시합니다."
L["config_zeppelin_horde"] = "호드 비행선"
L["config_zeppelin_horde_desc"] = "호드의 비행선 위치를 표시합니다."
L["Deeprun Tram to Ironforge"] = "아이언포지 방향 깊은굴 지하철"
L["Deeprun Tram to Stormwind"] = "스톰윈드 방향 깊은굴 지하철"
L["Zeppelin to Orgrimmar"] = "오그리마 방향 비행선"
L["Zeppelin to Stranglethorn Vale"] = "가시덤불 골짜기 방향 비행선"
L["Zeppelin to Undercity"] = "언더시티 방향 비행선"
end