local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide (BCC)", "ptBR", false, true)

if not L then return end
-- Brazilian Portuguese translation by D4MM0N1C https://www.curseforge.com/members/d4mm0n1c
if L then
L["Boat to Auberdine"] = "Barco para Auberdine"
L["Boat to Booty Bay"] = "Barco para Angra do Butim"
L["Boat to Darnassus"] = "Barco para Darnassus"
L["Boat to Menethil Harbor"] = "Barco para o Porto de Menethil"
L["Boat to Ratchet"] = "Barco para Vila Catraca"
L["Boat to Theramore"] = "Barco para Theramore"
L["config_boat"] = "Barco"
L["config_boat_alliance"] = "Barco da Aliança"
L["config_boat_alliance_desc"] = "Mostrar a localização dos barcos da Aliança."
L["config_boat_desc"] = "Mostrar a localização dos barcos"
L["config_easy_waypoints"] = "Pontos de destino facilitados"
L["config_easy_waypoints_desc"] = "Ativa a criação de pontos de destino simplificado. \\nPermite que você defina um ponto de destino simplesmente clicando com o botão direito do mouse e acessa mais opções com CTRL + clique do botão direito."
L["config_icon_alpha"] = "Alfa do Ícone"
L["config_icon_alpha_desc"] = "A transparência alfa dos ícones"
L["config_icon_scale"] = "Escala do Ícone"
L["config_icon_scale_desc"] = "A escala dos ícones"
L["config_note"] = "Nota"
L["config_note_desc"] = "Mostrar notas adicionais dos pontos assim que ficarem disponíveis."
L["config_plugin_desc"] = "Mostrar as localizações dos barcos e zepelins no Mapa-múndi e no Minimapa"
L["config_restore_nodes"] = "Restaurar os pontos ocultos"
L["config_restore_nodes_desc"] = "Mostrar todos os pontos que você ocultou manualmente clicando com o botão direito do mouse e escolhendo \"ocultar\"."
L["config_tram"] = "Metrô Correfundo"
L["config_tram_desc"] = "Mostrar as localizações do Metrô Correfundo em Ventobravo e Altaforja."
L["config_what_to_display"] = "O que mostrar?"
L["config_what_to_display_desc"] = "Estas configurações controlam que tipos de ícones serão mostrados."
L["config_zeppelin"] = "Zepelin"
L["config_zeppelin_desc"] = "Mostrar a localização dos zepelins."
L["config_zeppelin_horde"] = "Zepelin da Horda"
L["config_zeppelin_horde_desc"] = "Mostrar a localização dos Zepelins da Horda."
L["Deeprun Tram to Ironforge"] = "Metrô Correfundo para Altaforja"
L["Deeprun Tram to Stormwind"] = "Metrô Correfundo para Ventobravo"
L["Zeppelin to Orgrimmar"] = "Zepelin para Orgrimmar"
L["Zeppelin to Stranglethorn Vale"] = "Zepelin para a Selva do Espinhaço"
L["Zeppelin to Undercity"] = "Zepelin para Cidade Baixa"
end