local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide (BCC)", "ruRU", false, true)

if not L then return end
-- Russian translation by Кеаллах RU-Змейталак https://www.curseforge.com/members/arrogant_dreamer
if L then
L["Boat to Auberdine"] = "Корабль в Аубердин"
L["Boat to Booty Bay"] = "Корабль в Пиратскую бухту"
L["Boat to Darnassus"] = "Корабль в Дарнас"
L["Boat to Menethil Harbor"] = "Корабль в Гавань Менетилов"
L["Boat to Ratchet"] = "Корабль в Кабестан"
L["Boat to Theramore"] = "Корабль на остров Терамор"
L["config_boat"] = "Корабль"
L["config_boat_alliance"] = "Корабли Альянса"
L["config_boat_alliance_desc"] = "Показать места швартовки кораблей Альянса"
L["config_boat_desc"] = "Показать места швартовки кораблей"
L["config_easy_waypoints"] = "Легкие путевые точки"
L["config_easy_waypoints_desc"] = "Активирует упрощенное создание путевой точки. Позволяет установить маршрутную точку, щелкнув правой кнопкой мыши, и получить доступ к дополнительным параметрам, нажав CTRL + щелчок правой кнопкой мыши."
L["config_easy_waypoints_requires"] = "Требуется"
L["config_icon_alpha"] = "Прозрачность значка"
L["config_icon_alpha_desc"] = "Прозрачность значков"
L["config_icon_scale"] = "Размер значка"
L["config_icon_scale_desc"] = "Размер значков "
L["config_note"] = "Заметка "
L["config_note_desc"] = "Показать дополнительные заметки узла, когда они доступны."
L["config_plugin_desc"] = "Показать расположение кораблей и дирижаблей на карте мира и на миникарте."
L["config_restore_nodes"] = "Восстановить скрытые узлы"
L["config_restore_nodes_desc"] = "Восстановите все узлы, которые были скрыты через контекстное меню."
L["config_restore_nodes_print"] = "Все скрытые узлы были восстановлены"
L["config_tab_general"] = "Общий"
L["config_tab_scale_alpha"] = "Размер / Прозрачность"
L["config_tram"] = "Подземный поезд"
L["config_tram_desc"] = "Показать Подземный поезд из Штормград в Стальгорн"
L["config_what_to_display"] = "Что отображать?"
L["config_what_to_display_desc"] = "Эти настройки определяют тип отображаемых значков"
L["config_zeppelin"] = "Дирижабль"
L["config_zeppelin_desc"] = "оказать воздушные гавани дирижаблей"
L["config_zeppelin_horde"] = "Дирижабли Орды"
L["config_zeppelin_horde_desc"] = "Показать воздушные гавани дирижаблей Орды"
L["Deeprun Tram to Ironforge"] = "Подземный поезд в Стальгорн"
L["Deeprun Tram to Stormwind"] = "Подземный поезд в Штормград"
L["handler_context_menu_add_tomtom"] = "Добавить в TomTom"
L["handler_context_menu_hide_node"] = "Скрыть этот узел"
L["Zeppelin to Orgrimmar"] = "Дирижабль в Оргриммар"
L["Zeppelin to Stranglethorn Vale"] = "Дирижабль в Тернистую долину"
L["Zeppelin to Undercity"] = "Дирижабль в Подгород"
end