if GetLocale() ~= "itIT" then return end
if not DBM_COMMON_L then DBM_COMMON_L = {} end

local CL = DBM_COMMON_L

CL.NEXT						= "Avanti %s"
CL.COOLDOWN					= "%s CD"
CL.UNKNOWN					= "sconosciuto" -- UNKNOWN which is "Unknown" (does u vs U matter?)
CL.LEFT						= "Sinistra"
CL.RIGHT					= "Destra"
CL.BOTH						= "Entrambi"
CL.BACK						= "Indietro"--BACK
CL.SIDE						= "Lato"
CL.TOP						= "Cima"
CL.BOTTOM					= "Fondo"
CL.MIDDLE					= "Mezzo"
CL.FRONT					= "Fronte"
CL.EAST						= "Est"
CL.WEST						= "Ovest"
CL.NORTH					= "Nord"
CL.SOUTH					= "Sud"
CL.INTERMISSION				= "Interfase" -- No blizz global for this, and will probably be used in most end tier fights with intermission phases
CL.ORB						= "Sfera"
CL.CHEST					= "Cassa" -- As in Treasure 'Chest'. Not Chest as in body part.
CL.NO_DEBUFF				= "No %s"--For use in places like info frame where you put "Not Spellname"
CL.ALLY						= "Alleato" -- Such as "Move to Ally"
CL.ADD						= "Add" -- A fight Add as in "boss spawned extra adds"
CL.ADDS						= "Adds"
CL.BIG_ADD					= "Add Grande"
CL.BOSS						= "Boss"
CL.EDGE						= "Bordo Stanza"
CL.FAR_AWAY					= "Lontano"
CL.BREAK_LOS				= "Interrompi LOS"
CL.RESTORE_LOS				= "Ripristina/Mantieni LOS"
CL.SAFE						= "Sicuro"
CL.NOTSAFE					= "Non Sicuro"
CL.SHIELD					= "Scudo"
CL.INCOMING					= "%s in Arrivo"
CL.BOSSTOGETHER				= "Bosses Together"
CL.BOSSAPART				= "Bosses Apart"
